package com.jisu.WeChatApp.pojo;

import java.util.ArrayList;
import java.util.List;

public class BestServerClassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public BestServerClassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBestServerClassIdIsNull() {
            addCriterion("best_server_class_id is null");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdIsNotNull() {
            addCriterion("best_server_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdEqualTo(String value) {
            addCriterion("best_server_class_id =", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdNotEqualTo(String value) {
            addCriterion("best_server_class_id <>", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdGreaterThan(String value) {
            addCriterion("best_server_class_id >", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdGreaterThanOrEqualTo(String value) {
            addCriterion("best_server_class_id >=", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdLessThan(String value) {
            addCriterion("best_server_class_id <", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdLessThanOrEqualTo(String value) {
            addCriterion("best_server_class_id <=", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdLike(String value) {
            addCriterion("best_server_class_id like", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdNotLike(String value) {
            addCriterion("best_server_class_id not like", value, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdIn(List<String> values) {
            addCriterion("best_server_class_id in", values, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdNotIn(List<String> values) {
            addCriterion("best_server_class_id not in", values, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdBetween(String value1, String value2) {
            addCriterion("best_server_class_id between", value1, value2, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andBestServerClassIdNotBetween(String value1, String value2) {
            addCriterion("best_server_class_id not between", value1, value2, "bestServerClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdIsNull() {
            addCriterion("server_class_id is null");
            return (Criteria) this;
        }

        public Criteria andServerClassIdIsNotNull() {
            addCriterion("server_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerClassIdEqualTo(String value) {
            addCriterion("server_class_id =", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotEqualTo(String value) {
            addCriterion("server_class_id <>", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdGreaterThan(String value) {
            addCriterion("server_class_id >", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdGreaterThanOrEqualTo(String value) {
            addCriterion("server_class_id >=", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdLessThan(String value) {
            addCriterion("server_class_id <", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdLessThanOrEqualTo(String value) {
            addCriterion("server_class_id <=", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdLike(String value) {
            addCriterion("server_class_id like", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotLike(String value) {
            addCriterion("server_class_id not like", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdIn(List<String> values) {
            addCriterion("server_class_id in", values, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotIn(List<String> values) {
            addCriterion("server_class_id not in", values, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdBetween(String value1, String value2) {
            addCriterion("server_class_id between", value1, value2, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotBetween(String value1, String value2) {
            addCriterion("server_class_id not between", value1, value2, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNull() {
            addCriterion("member_no is null");
            return (Criteria) this;
        }

        public Criteria andMemberNoIsNotNull() {
            addCriterion("member_no is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNoEqualTo(String value) {
            addCriterion("member_no =", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotEqualTo(String value) {
            addCriterion("member_no <>", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThan(String value) {
            addCriterion("member_no >", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
            addCriterion("member_no >=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThan(String value) {
            addCriterion("member_no <", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLessThanOrEqualTo(String value) {
            addCriterion("member_no <=", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoLike(String value) {
            addCriterion("member_no like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotLike(String value) {
            addCriterion("member_no not like", value, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoIn(List<String> values) {
            addCriterion("member_no in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotIn(List<String> values) {
            addCriterion("member_no not in", values, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoBetween(String value1, String value2) {
            addCriterion("member_no between", value1, value2, "memberNo");
            return (Criteria) this;
        }

        public Criteria andMemberNoNotBetween(String value1, String value2) {
            addCriterion("member_no not between", value1, value2, "memberNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table best_server_class
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table best_server_class
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}