package com.jisu.WeChatApp.pojo;

import java.util.Date;

public class CommentInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_info.comment_id
	 * @mbg.generated
	 */
	private String commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_info.comment_text
	 * @mbg.generated
	 */
	private String commentText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_info.comment_type
	 * @mbg.generated
	 */
	private Integer commentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_info.member_no
	 * @mbg.generated
	 */
	private String memberNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_info.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_info.relation_id
	 * @mbg.generated
	 */
	private String relationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_info.praise_points
	 * @mbg.generated
	 */
	private Integer praisePoints;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_info.comment_id
	 * @return  the value of comment_info.comment_id
	 * @mbg.generated
	 */
	public String getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_info.comment_id
	 * @param commentId  the value for comment_info.comment_id
	 * @mbg.generated
	 */
	public void setCommentId(String commentId) {
		this.commentId = commentId == null ? null : commentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_info.comment_text
	 * @return  the value of comment_info.comment_text
	 * @mbg.generated
	 */
	public String getCommentText() {
		return commentText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_info.comment_text
	 * @param commentText  the value for comment_info.comment_text
	 * @mbg.generated
	 */
	public void setCommentText(String commentText) {
		this.commentText = commentText == null ? null : commentText.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_info.comment_type
	 * @return  the value of comment_info.comment_type
	 * @mbg.generated
	 */
	public Integer getCommentType() {
		return commentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_info.comment_type
	 * @param commentType  the value for comment_info.comment_type
	 * @mbg.generated
	 */
	public void setCommentType(Integer commentType) {
		this.commentType = commentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_info.member_no
	 * @return  the value of comment_info.member_no
	 * @mbg.generated
	 */
	public String getMemberNo() {
		return memberNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_info.member_no
	 * @param memberNo  the value for comment_info.member_no
	 * @mbg.generated
	 */
	public void setMemberNo(String memberNo) {
		this.memberNo = memberNo == null ? null : memberNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_info.create_time
	 * @return  the value of comment_info.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_info.create_time
	 * @param createTime  the value for comment_info.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_info.relation_id
	 * @return  the value of comment_info.relation_id
	 * @mbg.generated
	 */
	public String getRelationId() {
		return relationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_info.relation_id
	 * @param relationId  the value for comment_info.relation_id
	 * @mbg.generated
	 */
	public void setRelationId(String relationId) {
		this.relationId = relationId == null ? null : relationId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_info.praise_points
	 * @return  the value of comment_info.praise_points
	 * @mbg.generated
	 */
	public Integer getPraisePoints() {
		return praisePoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_info.praise_points
	 * @param praisePoints  the value for comment_info.praise_points
	 * @mbg.generated
	 */
	public void setPraisePoints(Integer praisePoints) {
		this.praisePoints = praisePoints;
	}
}