package com.jisu.WeChatApp.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public CommentInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCommentIdIsNull() {
			addCriterion("comment_id is null");
			return (Criteria) this;
		}

		public Criteria andCommentIdIsNotNull() {
			addCriterion("comment_id is not null");
			return (Criteria) this;
		}

		public Criteria andCommentIdEqualTo(String value) {
			addCriterion("comment_id =", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotEqualTo(String value) {
			addCriterion("comment_id <>", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdGreaterThan(String value) {
			addCriterion("comment_id >", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdGreaterThanOrEqualTo(String value) {
			addCriterion("comment_id >=", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdLessThan(String value) {
			addCriterion("comment_id <", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdLessThanOrEqualTo(String value) {
			addCriterion("comment_id <=", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdLike(String value) {
			addCriterion("comment_id like", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotLike(String value) {
			addCriterion("comment_id not like", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdIn(List<String> values) {
			addCriterion("comment_id in", values, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotIn(List<String> values) {
			addCriterion("comment_id not in", values, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdBetween(String value1, String value2) {
			addCriterion("comment_id between", value1, value2, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotBetween(String value1, String value2) {
			addCriterion("comment_id not between", value1, value2, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentTextIsNull() {
			addCriterion("comment_text is null");
			return (Criteria) this;
		}

		public Criteria andCommentTextIsNotNull() {
			addCriterion("comment_text is not null");
			return (Criteria) this;
		}

		public Criteria andCommentTextEqualTo(String value) {
			addCriterion("comment_text =", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextNotEqualTo(String value) {
			addCriterion("comment_text <>", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextGreaterThan(String value) {
			addCriterion("comment_text >", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextGreaterThanOrEqualTo(String value) {
			addCriterion("comment_text >=", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextLessThan(String value) {
			addCriterion("comment_text <", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextLessThanOrEqualTo(String value) {
			addCriterion("comment_text <=", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextLike(String value) {
			addCriterion("comment_text like", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextNotLike(String value) {
			addCriterion("comment_text not like", value, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextIn(List<String> values) {
			addCriterion("comment_text in", values, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextNotIn(List<String> values) {
			addCriterion("comment_text not in", values, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextBetween(String value1, String value2) {
			addCriterion("comment_text between", value1, value2, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTextNotBetween(String value1, String value2) {
			addCriterion("comment_text not between", value1, value2, "commentText");
			return (Criteria) this;
		}

		public Criteria andCommentTypeIsNull() {
			addCriterion("comment_type is null");
			return (Criteria) this;
		}

		public Criteria andCommentTypeIsNotNull() {
			addCriterion("comment_type is not null");
			return (Criteria) this;
		}

		public Criteria andCommentTypeEqualTo(Integer value) {
			addCriterion("comment_type =", value, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeNotEqualTo(Integer value) {
			addCriterion("comment_type <>", value, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeGreaterThan(Integer value) {
			addCriterion("comment_type >", value, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("comment_type >=", value, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeLessThan(Integer value) {
			addCriterion("comment_type <", value, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeLessThanOrEqualTo(Integer value) {
			addCriterion("comment_type <=", value, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeIn(List<Integer> values) {
			addCriterion("comment_type in", values, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeNotIn(List<Integer> values) {
			addCriterion("comment_type not in", values, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeBetween(Integer value1, Integer value2) {
			addCriterion("comment_type between", value1, value2, "commentType");
			return (Criteria) this;
		}

		public Criteria andCommentTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("comment_type not between", value1, value2, "commentType");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNull() {
			addCriterion("member_no is null");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNotNull() {
			addCriterion("member_no is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNoEqualTo(String value) {
			addCriterion("member_no =", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotEqualTo(String value) {
			addCriterion("member_no <>", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThan(String value) {
			addCriterion("member_no >", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
			addCriterion("member_no >=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThan(String value) {
			addCriterion("member_no <", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThanOrEqualTo(String value) {
			addCriterion("member_no <=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLike(String value) {
			addCriterion("member_no like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotLike(String value) {
			addCriterion("member_no not like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoIn(List<String> values) {
			addCriterion("member_no in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotIn(List<String> values) {
			addCriterion("member_no not in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoBetween(String value1, String value2) {
			addCriterion("member_no between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotBetween(String value1, String value2) {
			addCriterion("member_no not between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andRelationIdIsNull() {
			addCriterion("relation_id is null");
			return (Criteria) this;
		}

		public Criteria andRelationIdIsNotNull() {
			addCriterion("relation_id is not null");
			return (Criteria) this;
		}

		public Criteria andRelationIdEqualTo(String value) {
			addCriterion("relation_id =", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdNotEqualTo(String value) {
			addCriterion("relation_id <>", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdGreaterThan(String value) {
			addCriterion("relation_id >", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdGreaterThanOrEqualTo(String value) {
			addCriterion("relation_id >=", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdLessThan(String value) {
			addCriterion("relation_id <", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdLessThanOrEqualTo(String value) {
			addCriterion("relation_id <=", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdLike(String value) {
			addCriterion("relation_id like", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdNotLike(String value) {
			addCriterion("relation_id not like", value, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdIn(List<String> values) {
			addCriterion("relation_id in", values, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdNotIn(List<String> values) {
			addCriterion("relation_id not in", values, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdBetween(String value1, String value2) {
			addCriterion("relation_id between", value1, value2, "relationId");
			return (Criteria) this;
		}

		public Criteria andRelationIdNotBetween(String value1, String value2) {
			addCriterion("relation_id not between", value1, value2, "relationId");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIsNull() {
			addCriterion("praise_points is null");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIsNotNull() {
			addCriterion("praise_points is not null");
			return (Criteria) this;
		}

		public Criteria andPraisePointsEqualTo(Integer value) {
			addCriterion("praise_points =", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotEqualTo(Integer value) {
			addCriterion("praise_points <>", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsGreaterThan(Integer value) {
			addCriterion("praise_points >", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsGreaterThanOrEqualTo(Integer value) {
			addCriterion("praise_points >=", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsLessThan(Integer value) {
			addCriterion("praise_points <", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsLessThanOrEqualTo(Integer value) {
			addCriterion("praise_points <=", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIn(List<Integer> values) {
			addCriterion("praise_points in", values, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotIn(List<Integer> values) {
			addCriterion("praise_points not in", values, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsBetween(Integer value1, Integer value2) {
			addCriterion("praise_points between", value1, value2, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotBetween(Integer value1, Integer value2) {
			addCriterion("praise_points not between", value1, value2, "praisePoints");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}