package com.jisu.WeChatApp.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExperienceInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table experience_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table experience_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table experience_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public ExperienceInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table experience_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andExperienceIdIsNull() {
			addCriterion("experience_id is null");
			return (Criteria) this;
		}

		public Criteria andExperienceIdIsNotNull() {
			addCriterion("experience_id is not null");
			return (Criteria) this;
		}

		public Criteria andExperienceIdEqualTo(String value) {
			addCriterion("experience_id =", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdNotEqualTo(String value) {
			addCriterion("experience_id <>", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdGreaterThan(String value) {
			addCriterion("experience_id >", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdGreaterThanOrEqualTo(String value) {
			addCriterion("experience_id >=", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdLessThan(String value) {
			addCriterion("experience_id <", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdLessThanOrEqualTo(String value) {
			addCriterion("experience_id <=", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdLike(String value) {
			addCriterion("experience_id like", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdNotLike(String value) {
			addCriterion("experience_id not like", value, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdIn(List<String> values) {
			addCriterion("experience_id in", values, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdNotIn(List<String> values) {
			addCriterion("experience_id not in", values, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdBetween(String value1, String value2) {
			addCriterion("experience_id between", value1, value2, "experienceId");
			return (Criteria) this;
		}

		public Criteria andExperienceIdNotBetween(String value1, String value2) {
			addCriterion("experience_id not between", value1, value2, "experienceId");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNull() {
			addCriterion("member_no is null");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNotNull() {
			addCriterion("member_no is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNoEqualTo(String value) {
			addCriterion("member_no =", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotEqualTo(String value) {
			addCriterion("member_no <>", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThan(String value) {
			addCriterion("member_no >", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
			addCriterion("member_no >=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThan(String value) {
			addCriterion("member_no <", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThanOrEqualTo(String value) {
			addCriterion("member_no <=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLike(String value) {
			addCriterion("member_no like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotLike(String value) {
			addCriterion("member_no not like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoIn(List<String> values) {
			addCriterion("member_no in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotIn(List<String> values) {
			addCriterion("member_no not in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoBetween(String value1, String value2) {
			addCriterion("member_no between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotBetween(String value1, String value2) {
			addCriterion("member_no not between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andTextUrlIsNull() {
			addCriterion("text_url is null");
			return (Criteria) this;
		}

		public Criteria andTextUrlIsNotNull() {
			addCriterion("text_url is not null");
			return (Criteria) this;
		}

		public Criteria andTextUrlEqualTo(String value) {
			addCriterion("text_url =", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlNotEqualTo(String value) {
			addCriterion("text_url <>", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlGreaterThan(String value) {
			addCriterion("text_url >", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlGreaterThanOrEqualTo(String value) {
			addCriterion("text_url >=", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlLessThan(String value) {
			addCriterion("text_url <", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlLessThanOrEqualTo(String value) {
			addCriterion("text_url <=", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlLike(String value) {
			addCriterion("text_url like", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlNotLike(String value) {
			addCriterion("text_url not like", value, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlIn(List<String> values) {
			addCriterion("text_url in", values, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlNotIn(List<String> values) {
			addCriterion("text_url not in", values, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlBetween(String value1, String value2) {
			addCriterion("text_url between", value1, value2, "textUrl");
			return (Criteria) this;
		}

		public Criteria andTextUrlNotBetween(String value1, String value2) {
			addCriterion("text_url not between", value1, value2, "textUrl");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoIsNull() {
			addCriterion("experience_photo is null");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoIsNotNull() {
			addCriterion("experience_photo is not null");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoEqualTo(String value) {
			addCriterion("experience_photo =", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoNotEqualTo(String value) {
			addCriterion("experience_photo <>", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoGreaterThan(String value) {
			addCriterion("experience_photo >", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoGreaterThanOrEqualTo(String value) {
			addCriterion("experience_photo >=", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoLessThan(String value) {
			addCriterion("experience_photo <", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoLessThanOrEqualTo(String value) {
			addCriterion("experience_photo <=", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoLike(String value) {
			addCriterion("experience_photo like", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoNotLike(String value) {
			addCriterion("experience_photo not like", value, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoIn(List<String> values) {
			addCriterion("experience_photo in", values, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoNotIn(List<String> values) {
			addCriterion("experience_photo not in", values, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoBetween(String value1, String value2) {
			addCriterion("experience_photo between", value1, value2, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andExperiencePhotoNotBetween(String value1, String value2) {
			addCriterion("experience_photo not between", value1, value2, "experiencePhoto");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIsNull() {
			addCriterion("praise_points is null");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIsNotNull() {
			addCriterion("praise_points is not null");
			return (Criteria) this;
		}

		public Criteria andPraisePointsEqualTo(Integer value) {
			addCriterion("praise_points =", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotEqualTo(Integer value) {
			addCriterion("praise_points <>", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsGreaterThan(Integer value) {
			addCriterion("praise_points >", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsGreaterThanOrEqualTo(Integer value) {
			addCriterion("praise_points >=", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsLessThan(Integer value) {
			addCriterion("praise_points <", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsLessThanOrEqualTo(Integer value) {
			addCriterion("praise_points <=", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIn(List<Integer> values) {
			addCriterion("praise_points in", values, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotIn(List<Integer> values) {
			addCriterion("praise_points not in", values, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsBetween(Integer value1, Integer value2) {
			addCriterion("praise_points between", value1, value2, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotBetween(Integer value1, Integer value2) {
			addCriterion("praise_points not between", value1, value2, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andExperienceDescIsNull() {
			addCriterion("experience_desc is null");
			return (Criteria) this;
		}

		public Criteria andExperienceDescIsNotNull() {
			addCriterion("experience_desc is not null");
			return (Criteria) this;
		}

		public Criteria andExperienceDescEqualTo(String value) {
			addCriterion("experience_desc =", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescNotEqualTo(String value) {
			addCriterion("experience_desc <>", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescGreaterThan(String value) {
			addCriterion("experience_desc >", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescGreaterThanOrEqualTo(String value) {
			addCriterion("experience_desc >=", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescLessThan(String value) {
			addCriterion("experience_desc <", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescLessThanOrEqualTo(String value) {
			addCriterion("experience_desc <=", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescLike(String value) {
			addCriterion("experience_desc like", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescNotLike(String value) {
			addCriterion("experience_desc not like", value, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescIn(List<String> values) {
			addCriterion("experience_desc in", values, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescNotIn(List<String> values) {
			addCriterion("experience_desc not in", values, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescBetween(String value1, String value2) {
			addCriterion("experience_desc between", value1, value2, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andExperienceDescNotBetween(String value1, String value2) {
			addCriterion("experience_desc not between", value1, value2, "experienceDesc");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("order_id like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("order_id not like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andServerClassId1IsNull() {
			addCriterion("server_class_id_1 is null");
			return (Criteria) this;
		}

		public Criteria andServerClassId1IsNotNull() {
			addCriterion("server_class_id_1 is not null");
			return (Criteria) this;
		}

		public Criteria andServerClassId1EqualTo(String value) {
			addCriterion("server_class_id_1 =", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1NotEqualTo(String value) {
			addCriterion("server_class_id_1 <>", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1GreaterThan(String value) {
			addCriterion("server_class_id_1 >", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1GreaterThanOrEqualTo(String value) {
			addCriterion("server_class_id_1 >=", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1LessThan(String value) {
			addCriterion("server_class_id_1 <", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1LessThanOrEqualTo(String value) {
			addCriterion("server_class_id_1 <=", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1Like(String value) {
			addCriterion("server_class_id_1 like", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1NotLike(String value) {
			addCriterion("server_class_id_1 not like", value, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1In(List<String> values) {
			addCriterion("server_class_id_1 in", values, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1NotIn(List<String> values) {
			addCriterion("server_class_id_1 not in", values, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1Between(String value1, String value2) {
			addCriterion("server_class_id_1 between", value1, value2, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId1NotBetween(String value1, String value2) {
			addCriterion("server_class_id_1 not between", value1, value2, "serverClassId1");
			return (Criteria) this;
		}

		public Criteria andServerClassId2IsNull() {
			addCriterion("server_class_id_2 is null");
			return (Criteria) this;
		}

		public Criteria andServerClassId2IsNotNull() {
			addCriterion("server_class_id_2 is not null");
			return (Criteria) this;
		}

		public Criteria andServerClassId2EqualTo(String value) {
			addCriterion("server_class_id_2 =", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2NotEqualTo(String value) {
			addCriterion("server_class_id_2 <>", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2GreaterThan(String value) {
			addCriterion("server_class_id_2 >", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2GreaterThanOrEqualTo(String value) {
			addCriterion("server_class_id_2 >=", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2LessThan(String value) {
			addCriterion("server_class_id_2 <", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2LessThanOrEqualTo(String value) {
			addCriterion("server_class_id_2 <=", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2Like(String value) {
			addCriterion("server_class_id_2 like", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2NotLike(String value) {
			addCriterion("server_class_id_2 not like", value, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2In(List<String> values) {
			addCriterion("server_class_id_2 in", values, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2NotIn(List<String> values) {
			addCriterion("server_class_id_2 not in", values, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2Between(String value1, String value2) {
			addCriterion("server_class_id_2 between", value1, value2, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId2NotBetween(String value1, String value2) {
			addCriterion("server_class_id_2 not between", value1, value2, "serverClassId2");
			return (Criteria) this;
		}

		public Criteria andServerClassId3IsNull() {
			addCriterion("server_class_id_3 is null");
			return (Criteria) this;
		}

		public Criteria andServerClassId3IsNotNull() {
			addCriterion("server_class_id_3 is not null");
			return (Criteria) this;
		}

		public Criteria andServerClassId3EqualTo(String value) {
			addCriterion("server_class_id_3 =", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3NotEqualTo(String value) {
			addCriterion("server_class_id_3 <>", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3GreaterThan(String value) {
			addCriterion("server_class_id_3 >", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3GreaterThanOrEqualTo(String value) {
			addCriterion("server_class_id_3 >=", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3LessThan(String value) {
			addCriterion("server_class_id_3 <", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3LessThanOrEqualTo(String value) {
			addCriterion("server_class_id_3 <=", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3Like(String value) {
			addCriterion("server_class_id_3 like", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3NotLike(String value) {
			addCriterion("server_class_id_3 not like", value, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3In(List<String> values) {
			addCriterion("server_class_id_3 in", values, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3NotIn(List<String> values) {
			addCriterion("server_class_id_3 not in", values, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3Between(String value1, String value2) {
			addCriterion("server_class_id_3 between", value1, value2, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId3NotBetween(String value1, String value2) {
			addCriterion("server_class_id_3 not between", value1, value2, "serverClassId3");
			return (Criteria) this;
		}

		public Criteria andServerClassId4IsNull() {
			addCriterion("server_class_id_4 is null");
			return (Criteria) this;
		}

		public Criteria andServerClassId4IsNotNull() {
			addCriterion("server_class_id_4 is not null");
			return (Criteria) this;
		}

		public Criteria andServerClassId4EqualTo(String value) {
			addCriterion("server_class_id_4 =", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4NotEqualTo(String value) {
			addCriterion("server_class_id_4 <>", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4GreaterThan(String value) {
			addCriterion("server_class_id_4 >", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4GreaterThanOrEqualTo(String value) {
			addCriterion("server_class_id_4 >=", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4LessThan(String value) {
			addCriterion("server_class_id_4 <", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4LessThanOrEqualTo(String value) {
			addCriterion("server_class_id_4 <=", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4Like(String value) {
			addCriterion("server_class_id_4 like", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4NotLike(String value) {
			addCriterion("server_class_id_4 not like", value, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4In(List<String> values) {
			addCriterion("server_class_id_4 in", values, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4NotIn(List<String> values) {
			addCriterion("server_class_id_4 not in", values, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4Between(String value1, String value2) {
			addCriterion("server_class_id_4 between", value1, value2, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId4NotBetween(String value1, String value2) {
			addCriterion("server_class_id_4 not between", value1, value2, "serverClassId4");
			return (Criteria) this;
		}

		public Criteria andServerClassId5IsNull() {
			addCriterion("server_class_id_5 is null");
			return (Criteria) this;
		}

		public Criteria andServerClassId5IsNotNull() {
			addCriterion("server_class_id_5 is not null");
			return (Criteria) this;
		}

		public Criteria andServerClassId5EqualTo(String value) {
			addCriterion("server_class_id_5 =", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5NotEqualTo(String value) {
			addCriterion("server_class_id_5 <>", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5GreaterThan(String value) {
			addCriterion("server_class_id_5 >", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5GreaterThanOrEqualTo(String value) {
			addCriterion("server_class_id_5 >=", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5LessThan(String value) {
			addCriterion("server_class_id_5 <", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5LessThanOrEqualTo(String value) {
			addCriterion("server_class_id_5 <=", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5Like(String value) {
			addCriterion("server_class_id_5 like", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5NotLike(String value) {
			addCriterion("server_class_id_5 not like", value, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5In(List<String> values) {
			addCriterion("server_class_id_5 in", values, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5NotIn(List<String> values) {
			addCriterion("server_class_id_5 not in", values, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5Between(String value1, String value2) {
			addCriterion("server_class_id_5 between", value1, value2, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerClassId5NotBetween(String value1, String value2) {
			addCriterion("server_class_id_5 not between", value1, value2, "serverClassId5");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoIsNull() {
			addCriterion("server_before_photo is null");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoIsNotNull() {
			addCriterion("server_before_photo is not null");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoEqualTo(String value) {
			addCriterion("server_before_photo =", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoNotEqualTo(String value) {
			addCriterion("server_before_photo <>", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoGreaterThan(String value) {
			addCriterion("server_before_photo >", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoGreaterThanOrEqualTo(String value) {
			addCriterion("server_before_photo >=", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoLessThan(String value) {
			addCriterion("server_before_photo <", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoLessThanOrEqualTo(String value) {
			addCriterion("server_before_photo <=", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoLike(String value) {
			addCriterion("server_before_photo like", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoNotLike(String value) {
			addCriterion("server_before_photo not like", value, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoIn(List<String> values) {
			addCriterion("server_before_photo in", values, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoNotIn(List<String> values) {
			addCriterion("server_before_photo not in", values, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoBetween(String value1, String value2) {
			addCriterion("server_before_photo between", value1, value2, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerBeforePhotoNotBetween(String value1, String value2) {
			addCriterion("server_before_photo not between", value1, value2, "serverBeforePhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoIsNull() {
			addCriterion("server_after_photo is null");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoIsNotNull() {
			addCriterion("server_after_photo is not null");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoEqualTo(String value) {
			addCriterion("server_after_photo =", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoNotEqualTo(String value) {
			addCriterion("server_after_photo <>", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoGreaterThan(String value) {
			addCriterion("server_after_photo >", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoGreaterThanOrEqualTo(String value) {
			addCriterion("server_after_photo >=", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoLessThan(String value) {
			addCriterion("server_after_photo <", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoLessThanOrEqualTo(String value) {
			addCriterion("server_after_photo <=", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoLike(String value) {
			addCriterion("server_after_photo like", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoNotLike(String value) {
			addCriterion("server_after_photo not like", value, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoIn(List<String> values) {
			addCriterion("server_after_photo in", values, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoNotIn(List<String> values) {
			addCriterion("server_after_photo not in", values, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoBetween(String value1, String value2) {
			addCriterion("server_after_photo between", value1, value2, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerAfterPhotoNotBetween(String value1, String value2) {
			addCriterion("server_after_photo not between", value1, value2, "serverAfterPhoto");
			return (Criteria) this;
		}

		public Criteria andServerConditionIsNull() {
			addCriterion("server_condition is null");
			return (Criteria) this;
		}

		public Criteria andServerConditionIsNotNull() {
			addCriterion("server_condition is not null");
			return (Criteria) this;
		}

		public Criteria andServerConditionEqualTo(String value) {
			addCriterion("server_condition =", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionNotEqualTo(String value) {
			addCriterion("server_condition <>", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionGreaterThan(String value) {
			addCriterion("server_condition >", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionGreaterThanOrEqualTo(String value) {
			addCriterion("server_condition >=", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionLessThan(String value) {
			addCriterion("server_condition <", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionLessThanOrEqualTo(String value) {
			addCriterion("server_condition <=", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionLike(String value) {
			addCriterion("server_condition like", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionNotLike(String value) {
			addCriterion("server_condition not like", value, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionIn(List<String> values) {
			addCriterion("server_condition in", values, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionNotIn(List<String> values) {
			addCriterion("server_condition not in", values, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionBetween(String value1, String value2) {
			addCriterion("server_condition between", value1, value2, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andServerConditionNotBetween(String value1, String value2) {
			addCriterion("server_condition not between", value1, value2, "serverCondition");
			return (Criteria) this;
		}

		public Criteria andShopServerIdIsNull() {
			addCriterion("shop_server_id is null");
			return (Criteria) this;
		}

		public Criteria andShopServerIdIsNotNull() {
			addCriterion("shop_server_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopServerIdEqualTo(String value) {
			addCriterion("shop_server_id =", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotEqualTo(String value) {
			addCriterion("shop_server_id <>", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdGreaterThan(String value) {
			addCriterion("shop_server_id >", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdGreaterThanOrEqualTo(String value) {
			addCriterion("shop_server_id >=", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdLessThan(String value) {
			addCriterion("shop_server_id <", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdLessThanOrEqualTo(String value) {
			addCriterion("shop_server_id <=", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdLike(String value) {
			addCriterion("shop_server_id like", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotLike(String value) {
			addCriterion("shop_server_id not like", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdIn(List<String> values) {
			addCriterion("shop_server_id in", values, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotIn(List<String> values) {
			addCriterion("shop_server_id not in", values, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdBetween(String value1, String value2) {
			addCriterion("shop_server_id between", value1, value2, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotBetween(String value1, String value2) {
			addCriterion("shop_server_id not between", value1, value2, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andServerNameIsNull() {
			addCriterion("server_name is null");
			return (Criteria) this;
		}

		public Criteria andServerNameIsNotNull() {
			addCriterion("server_name is not null");
			return (Criteria) this;
		}

		public Criteria andServerNameEqualTo(String value) {
			addCriterion("server_name =", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotEqualTo(String value) {
			addCriterion("server_name <>", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameGreaterThan(String value) {
			addCriterion("server_name >", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameGreaterThanOrEqualTo(String value) {
			addCriterion("server_name >=", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLessThan(String value) {
			addCriterion("server_name <", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLessThanOrEqualTo(String value) {
			addCriterion("server_name <=", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLike(String value) {
			addCriterion("server_name like", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotLike(String value) {
			addCriterion("server_name not like", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameIn(List<String> values) {
			addCriterion("server_name in", values, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotIn(List<String> values) {
			addCriterion("server_name not in", values, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameBetween(String value1, String value2) {
			addCriterion("server_name between", value1, value2, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotBetween(String value1, String value2) {
			addCriterion("server_name not between", value1, value2, "serverName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table experience_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table experience_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}