package com.jisu.WeChatApp.pojo;

import java.util.Date;

public class FormInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column form_info.form_info_id
	 * @mbg.generated
	 */
	private String formInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column form_info.form_id
	 * @mbg.generated
	 */
	private String formId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column form_info.open_id
	 * @mbg.generated
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column form_info.is_use
	 * @mbg.generated
	 */
	private Integer isUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column form_info.create_time
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column form_info.form_info_id
	 * @return  the value of form_info.form_info_id
	 * @mbg.generated
	 */
	public String getFormInfoId() {
		return formInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column form_info.form_info_id
	 * @param formInfoId  the value for form_info.form_info_id
	 * @mbg.generated
	 */
	public void setFormInfoId(String formInfoId) {
		this.formInfoId = formInfoId == null ? null : formInfoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column form_info.form_id
	 * @return  the value of form_info.form_id
	 * @mbg.generated
	 */
	public String getFormId() {
		return formId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column form_info.form_id
	 * @param formId  the value for form_info.form_id
	 * @mbg.generated
	 */
	public void setFormId(String formId) {
		this.formId = formId == null ? null : formId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column form_info.open_id
	 * @return  the value of form_info.open_id
	 * @mbg.generated
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column form_info.open_id
	 * @param openId  the value for form_info.open_id
	 * @mbg.generated
	 */
	public void setOpenId(String openId) {
		this.openId = openId == null ? null : openId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column form_info.is_use
	 * @return  the value of form_info.is_use
	 * @mbg.generated
	 */
	public Integer getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column form_info.is_use
	 * @param isUse  the value for form_info.is_use
	 * @mbg.generated
	 */
	public void setIsUse(Integer isUse) {
		this.isUse = isUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column form_info.create_time
	 * @return  the value of form_info.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column form_info.create_time
	 * @param createTime  the value for form_info.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}