package com.jisu.WeChatApp.pojo;

public class LableInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lable_info.lable_id
     *
     * @mbg.generated
     */
    private String lableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lable_info.lable_name
     *
     * @mbg.generated
     */
    private String lableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lable_info.lable_desc
     *
     * @mbg.generated
     */
    private String lableDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lable_info.lable_id
     *
     * @return the value of lable_info.lable_id
     *
     * @mbg.generated
     */
    public String getLableId() {
        return lableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lable_info.lable_id
     *
     * @param lableId the value for lable_info.lable_id
     *
     * @mbg.generated
     */
    public void setLableId(String lableId) {
        this.lableId = lableId == null ? null : lableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lable_info.lable_name
     *
     * @return the value of lable_info.lable_name
     *
     * @mbg.generated
     */
    public String getLableName() {
        return lableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lable_info.lable_name
     *
     * @param lableName the value for lable_info.lable_name
     *
     * @mbg.generated
     */
    public void setLableName(String lableName) {
        this.lableName = lableName == null ? null : lableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lable_info.lable_desc
     *
     * @return the value of lable_info.lable_desc
     *
     * @mbg.generated
     */
    public String getLableDesc() {
        return lableDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lable_info.lable_desc
     *
     * @param lableDesc the value for lable_info.lable_desc
     *
     * @mbg.generated
     */
    public void setLableDesc(String lableDesc) {
        this.lableDesc = lableDesc == null ? null : lableDesc.trim();
    }
}