package com.jisu.WeChatApp.pojo;

public class MemberProhi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_prohi.member_prohi_id
     *
     * @mbg.generated
     */
    private String memberProhiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_prohi.prohi_status
     *
     * @mbg.generated
     */
    private Integer prohiStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_prohi.prohi_type
     *
     * @mbg.generated
     */
    private Integer prohiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_prohi.member_no
     *
     * @mbg.generated
     */
    private String memberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_prohi.member_type
     *
     * @mbg.generated
     */
    private Integer memberType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_prohi.prohi_time
     *
     * @mbg.generated
     */
    private Integer prohiTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_prohi.member_prohi_id
     *
     * @return the value of member_prohi.member_prohi_id
     *
     * @mbg.generated
     */
    public String getMemberProhiId() {
        return memberProhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_prohi.member_prohi_id
     *
     * @param memberProhiId the value for member_prohi.member_prohi_id
     *
     * @mbg.generated
     */
    public void setMemberProhiId(String memberProhiId) {
        this.memberProhiId = memberProhiId == null ? null : memberProhiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_prohi.prohi_status
     *
     * @return the value of member_prohi.prohi_status
     *
     * @mbg.generated
     */
    public Integer getProhiStatus() {
        return prohiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_prohi.prohi_status
     *
     * @param prohiStatus the value for member_prohi.prohi_status
     *
     * @mbg.generated
     */
    public void setProhiStatus(Integer prohiStatus) {
        this.prohiStatus = prohiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_prohi.prohi_type
     *
     * @return the value of member_prohi.prohi_type
     *
     * @mbg.generated
     */
    public Integer getProhiType() {
        return prohiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_prohi.prohi_type
     *
     * @param prohiType the value for member_prohi.prohi_type
     *
     * @mbg.generated
     */
    public void setProhiType(Integer prohiType) {
        this.prohiType = prohiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_prohi.member_no
     *
     * @return the value of member_prohi.member_no
     *
     * @mbg.generated
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_prohi.member_no
     *
     * @param memberNo the value for member_prohi.member_no
     *
     * @mbg.generated
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_prohi.member_type
     *
     * @return the value of member_prohi.member_type
     *
     * @mbg.generated
     */
    public Integer getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_prohi.member_type
     *
     * @param memberType the value for member_prohi.member_type
     *
     * @mbg.generated
     */
    public void setMemberType(Integer memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_prohi.prohi_time
     *
     * @return the value of member_prohi.prohi_time
     *
     * @mbg.generated
     */
    public Integer getProhiTime() {
        return prohiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_prohi.prohi_time
     *
     * @param prohiTime the value for member_prohi.prohi_time
     *
     * @mbg.generated
     */
    public void setProhiTime(Integer prohiTime) {
        this.prohiTime = prohiTime;
    }
}