package com.jisu.WeChatApp.pojo;

public class MemberAddress {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.member_address_id
	 * @mbg.generated
	 */
	private String memberAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.member_no
	 * @mbg.generated
	 */
	private String memberNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.sheng_code
	 * @mbg.generated
	 */
	private String shengCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.shi_code
	 * @mbg.generated
	 */
	private String shiCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.qu_code
	 * @mbg.generated
	 */
	private String quCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.nickname
	 * @mbg.generated
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_address.is_default
	 * @mbg.generated
	 */
	private Integer isDefault;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.member_address_id
	 * @return  the value of member_address.member_address_id
	 * @mbg.generated
	 */
	public String getMemberAddressId() {
		return memberAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.member_address_id
	 * @param memberAddressId  the value for member_address.member_address_id
	 * @mbg.generated
	 */
	public void setMemberAddressId(String memberAddressId) {
		this.memberAddressId = memberAddressId == null ? null : memberAddressId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.member_no
	 * @return  the value of member_address.member_no
	 * @mbg.generated
	 */
	public String getMemberNo() {
		return memberNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.member_no
	 * @param memberNo  the value for member_address.member_no
	 * @mbg.generated
	 */
	public void setMemberNo(String memberNo) {
		this.memberNo = memberNo == null ? null : memberNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.address
	 * @return  the value of member_address.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.address
	 * @param address  the value for member_address.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.sheng_code
	 * @return  the value of member_address.sheng_code
	 * @mbg.generated
	 */
	public String getShengCode() {
		return shengCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.sheng_code
	 * @param shengCode  the value for member_address.sheng_code
	 * @mbg.generated
	 */
	public void setShengCode(String shengCode) {
		this.shengCode = shengCode == null ? null : shengCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.shi_code
	 * @return  the value of member_address.shi_code
	 * @mbg.generated
	 */
	public String getShiCode() {
		return shiCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.shi_code
	 * @param shiCode  the value for member_address.shi_code
	 * @mbg.generated
	 */
	public void setShiCode(String shiCode) {
		this.shiCode = shiCode == null ? null : shiCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.qu_code
	 * @return  the value of member_address.qu_code
	 * @mbg.generated
	 */
	public String getQuCode() {
		return quCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.qu_code
	 * @param quCode  the value for member_address.qu_code
	 * @mbg.generated
	 */
	public void setQuCode(String quCode) {
		this.quCode = quCode == null ? null : quCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.nickname
	 * @return  the value of member_address.nickname
	 * @mbg.generated
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.nickname
	 * @param nickname  the value for member_address.nickname
	 * @mbg.generated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.phone
	 * @return  the value of member_address.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.phone
	 * @param phone  the value for member_address.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_address.is_default
	 * @return  the value of member_address.is_default
	 * @mbg.generated
	 */
	public Integer getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_address.is_default
	 * @param isDefault  the value for member_address.is_default
	 * @mbg.generated
	 */
	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}
}