package com.jisu.WeChatApp.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_id
	 * @mbg.generated
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_code
	 * @mbg.generated
	 */
	private String orderCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.member_no
	 * @mbg.generated
	 */
	private String memberNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_price
	 * @mbg.generated
	 */
	private BigDecimal orderPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.pay_price
	 * @mbg.generated
	 */
	private BigDecimal payPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.pay_time
	 * @mbg.generated
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.shop_server_id
	 * @mbg.generated
	 */
	private String shopServerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_status
	 * @mbg.generated
	 */
	private Integer orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_type
	 * @mbg.generated
	 */
	private Integer orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_desc
	 * @mbg.generated
	 */
	private String orderDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.pay_way
	 * @mbg.generated
	 */
	private Integer payWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.server_time
	 * @mbg.generated
	 */
	private Date serverTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.close_time
	 * @mbg.generated
	 */
	private Date closeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.finish_time
	 * @mbg.generated
	 */
	private Date finishTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_num
	 * @mbg.generated
	 */
	private Integer orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.server_name
	 * @mbg.generated
	 */
	private String serverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.server_address
	 * @mbg.generated
	 */
	private String serverAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.shop_id
	 * @mbg.generated
	 */
	private String shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.server_member_no
	 * @mbg.generated
	 */
	private String serverMemberNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.shop_is_check
	 * @mbg.generated
	 */
	private Integer shopIsCheck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.server_memebr_is_chenck
	 * @mbg.generated
	 */
	private Integer serverMemebrIsChenck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.appointment_time_start
	 * @mbg.generated
	 */
	private Date appointmentTimeStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.appointment_time_end
	 * @mbg.generated
	 */
	private Date appointmentTimeEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.server_example_photo
	 * @mbg.generated
	 */
	private String serverExamplePhoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_phone
	 * @mbg.generated
	 */
	private String orderPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.order_nickname
	 * @mbg.generated
	 */
	private String orderNickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_info.server_member_name
	 * @mbg.generated
	 */
	private String serverMemberName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_id
	 * @return  the value of order_info.order_id
	 * @mbg.generated
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_id
	 * @param orderId  the value for order_info.order_id
	 * @mbg.generated
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_code
	 * @return  the value of order_info.order_code
	 * @mbg.generated
	 */
	public String getOrderCode() {
		return orderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_code
	 * @param orderCode  the value for order_info.order_code
	 * @mbg.generated
	 */
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode == null ? null : orderCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.member_no
	 * @return  the value of order_info.member_no
	 * @mbg.generated
	 */
	public String getMemberNo() {
		return memberNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.member_no
	 * @param memberNo  the value for order_info.member_no
	 * @mbg.generated
	 */
	public void setMemberNo(String memberNo) {
		this.memberNo = memberNo == null ? null : memberNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_price
	 * @return  the value of order_info.order_price
	 * @mbg.generated
	 */
	public BigDecimal getOrderPrice() {
		return orderPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_price
	 * @param orderPrice  the value for order_info.order_price
	 * @mbg.generated
	 */
	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.pay_price
	 * @return  the value of order_info.pay_price
	 * @mbg.generated
	 */
	public BigDecimal getPayPrice() {
		return payPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.pay_price
	 * @param payPrice  the value for order_info.pay_price
	 * @mbg.generated
	 */
	public void setPayPrice(BigDecimal payPrice) {
		this.payPrice = payPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.create_time
	 * @return  the value of order_info.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.create_time
	 * @param createTime  the value for order_info.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.pay_time
	 * @return  the value of order_info.pay_time
	 * @mbg.generated
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.pay_time
	 * @param payTime  the value for order_info.pay_time
	 * @mbg.generated
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.shop_server_id
	 * @return  the value of order_info.shop_server_id
	 * @mbg.generated
	 */
	public String getShopServerId() {
		return shopServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.shop_server_id
	 * @param shopServerId  the value for order_info.shop_server_id
	 * @mbg.generated
	 */
	public void setShopServerId(String shopServerId) {
		this.shopServerId = shopServerId == null ? null : shopServerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_status
	 * @return  the value of order_info.order_status
	 * @mbg.generated
	 */
	public Integer getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_status
	 * @param orderStatus  the value for order_info.order_status
	 * @mbg.generated
	 */
	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_type
	 * @return  the value of order_info.order_type
	 * @mbg.generated
	 */
	public Integer getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_type
	 * @param orderType  the value for order_info.order_type
	 * @mbg.generated
	 */
	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_desc
	 * @return  the value of order_info.order_desc
	 * @mbg.generated
	 */
	public String getOrderDesc() {
		return orderDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_desc
	 * @param orderDesc  the value for order_info.order_desc
	 * @mbg.generated
	 */
	public void setOrderDesc(String orderDesc) {
		this.orderDesc = orderDesc == null ? null : orderDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.pay_way
	 * @return  the value of order_info.pay_way
	 * @mbg.generated
	 */
	public Integer getPayWay() {
		return payWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.pay_way
	 * @param payWay  the value for order_info.pay_way
	 * @mbg.generated
	 */
	public void setPayWay(Integer payWay) {
		this.payWay = payWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.server_time
	 * @return  the value of order_info.server_time
	 * @mbg.generated
	 */
	public Date getServerTime() {
		return serverTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.server_time
	 * @param serverTime  the value for order_info.server_time
	 * @mbg.generated
	 */
	public void setServerTime(Date serverTime) {
		this.serverTime = serverTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.close_time
	 * @return  the value of order_info.close_time
	 * @mbg.generated
	 */
	public Date getCloseTime() {
		return closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.close_time
	 * @param closeTime  the value for order_info.close_time
	 * @mbg.generated
	 */
	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.finish_time
	 * @return  the value of order_info.finish_time
	 * @mbg.generated
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.finish_time
	 * @param finishTime  the value for order_info.finish_time
	 * @mbg.generated
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_num
	 * @return  the value of order_info.order_num
	 * @mbg.generated
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_num
	 * @param orderNum  the value for order_info.order_num
	 * @mbg.generated
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.server_name
	 * @return  the value of order_info.server_name
	 * @mbg.generated
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.server_name
	 * @param serverName  the value for order_info.server_name
	 * @mbg.generated
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName == null ? null : serverName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.server_address
	 * @return  the value of order_info.server_address
	 * @mbg.generated
	 */
	public String getServerAddress() {
		return serverAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.server_address
	 * @param serverAddress  the value for order_info.server_address
	 * @mbg.generated
	 */
	public void setServerAddress(String serverAddress) {
		this.serverAddress = serverAddress == null ? null : serverAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.shop_id
	 * @return  the value of order_info.shop_id
	 * @mbg.generated
	 */
	public String getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.shop_id
	 * @param shopId  the value for order_info.shop_id
	 * @mbg.generated
	 */
	public void setShopId(String shopId) {
		this.shopId = shopId == null ? null : shopId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.server_member_no
	 * @return  the value of order_info.server_member_no
	 * @mbg.generated
	 */
	public String getServerMemberNo() {
		return serverMemberNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.server_member_no
	 * @param serverMemberNo  the value for order_info.server_member_no
	 * @mbg.generated
	 */
	public void setServerMemberNo(String serverMemberNo) {
		this.serverMemberNo = serverMemberNo == null ? null : serverMemberNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.shop_is_check
	 * @return  the value of order_info.shop_is_check
	 * @mbg.generated
	 */
	public Integer getShopIsCheck() {
		return shopIsCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.shop_is_check
	 * @param shopIsCheck  the value for order_info.shop_is_check
	 * @mbg.generated
	 */
	public void setShopIsCheck(Integer shopIsCheck) {
		this.shopIsCheck = shopIsCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.server_memebr_is_chenck
	 * @return  the value of order_info.server_memebr_is_chenck
	 * @mbg.generated
	 */
	public Integer getServerMemebrIsChenck() {
		return serverMemebrIsChenck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.server_memebr_is_chenck
	 * @param serverMemebrIsChenck  the value for order_info.server_memebr_is_chenck
	 * @mbg.generated
	 */
	public void setServerMemebrIsChenck(Integer serverMemebrIsChenck) {
		this.serverMemebrIsChenck = serverMemebrIsChenck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.appointment_time_start
	 * @return  the value of order_info.appointment_time_start
	 * @mbg.generated
	 */
	public Date getAppointmentTimeStart() {
		return appointmentTimeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.appointment_time_start
	 * @param appointmentTimeStart  the value for order_info.appointment_time_start
	 * @mbg.generated
	 */
	public void setAppointmentTimeStart(Date appointmentTimeStart) {
		this.appointmentTimeStart = appointmentTimeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.appointment_time_end
	 * @return  the value of order_info.appointment_time_end
	 * @mbg.generated
	 */
	public Date getAppointmentTimeEnd() {
		return appointmentTimeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.appointment_time_end
	 * @param appointmentTimeEnd  the value for order_info.appointment_time_end
	 * @mbg.generated
	 */
	public void setAppointmentTimeEnd(Date appointmentTimeEnd) {
		this.appointmentTimeEnd = appointmentTimeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.server_example_photo
	 * @return  the value of order_info.server_example_photo
	 * @mbg.generated
	 */
	public String getServerExamplePhoto() {
		return serverExamplePhoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.server_example_photo
	 * @param serverExamplePhoto  the value for order_info.server_example_photo
	 * @mbg.generated
	 */
	public void setServerExamplePhoto(String serverExamplePhoto) {
		this.serverExamplePhoto = serverExamplePhoto == null ? null : serverExamplePhoto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_phone
	 * @return  the value of order_info.order_phone
	 * @mbg.generated
	 */
	public String getOrderPhone() {
		return orderPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_phone
	 * @param orderPhone  the value for order_info.order_phone
	 * @mbg.generated
	 */
	public void setOrderPhone(String orderPhone) {
		this.orderPhone = orderPhone == null ? null : orderPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.order_nickname
	 * @return  the value of order_info.order_nickname
	 * @mbg.generated
	 */
	public String getOrderNickname() {
		return orderNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.order_nickname
	 * @param orderNickname  the value for order_info.order_nickname
	 * @mbg.generated
	 */
	public void setOrderNickname(String orderNickname) {
		this.orderNickname = orderNickname == null ? null : orderNickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_info.server_member_name
	 * @return  the value of order_info.server_member_name
	 * @mbg.generated
	 */
	public String getServerMemberName() {
		return serverMemberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_info.server_member_name
	 * @param serverMemberName  the value for order_info.server_member_name
	 * @mbg.generated
	 */
	public void setServerMemberName(String serverMemberName) {
		this.serverMemberName = serverMemberName == null ? null : serverMemberName.trim();
	}
}