package com.jisu.WeChatApp.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public OrderInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("order_id like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("order_id not like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderCodeIsNull() {
			addCriterion("order_code is null");
			return (Criteria) this;
		}

		public Criteria andOrderCodeIsNotNull() {
			addCriterion("order_code is not null");
			return (Criteria) this;
		}

		public Criteria andOrderCodeEqualTo(String value) {
			addCriterion("order_code =", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeNotEqualTo(String value) {
			addCriterion("order_code <>", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeGreaterThan(String value) {
			addCriterion("order_code >", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
			addCriterion("order_code >=", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeLessThan(String value) {
			addCriterion("order_code <", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeLessThanOrEqualTo(String value) {
			addCriterion("order_code <=", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeLike(String value) {
			addCriterion("order_code like", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeNotLike(String value) {
			addCriterion("order_code not like", value, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeIn(List<String> values) {
			addCriterion("order_code in", values, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeNotIn(List<String> values) {
			addCriterion("order_code not in", values, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeBetween(String value1, String value2) {
			addCriterion("order_code between", value1, value2, "orderCode");
			return (Criteria) this;
		}

		public Criteria andOrderCodeNotBetween(String value1, String value2) {
			addCriterion("order_code not between", value1, value2, "orderCode");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNull() {
			addCriterion("member_no is null");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNotNull() {
			addCriterion("member_no is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNoEqualTo(String value) {
			addCriterion("member_no =", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotEqualTo(String value) {
			addCriterion("member_no <>", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThan(String value) {
			addCriterion("member_no >", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
			addCriterion("member_no >=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThan(String value) {
			addCriterion("member_no <", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThanOrEqualTo(String value) {
			addCriterion("member_no <=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLike(String value) {
			addCriterion("member_no like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotLike(String value) {
			addCriterion("member_no not like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoIn(List<String> values) {
			addCriterion("member_no in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotIn(List<String> values) {
			addCriterion("member_no not in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoBetween(String value1, String value2) {
			addCriterion("member_no between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotBetween(String value1, String value2) {
			addCriterion("member_no not between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andOrderPriceIsNull() {
			addCriterion("order_price is null");
			return (Criteria) this;
		}

		public Criteria andOrderPriceIsNotNull() {
			addCriterion("order_price is not null");
			return (Criteria) this;
		}

		public Criteria andOrderPriceEqualTo(BigDecimal value) {
			addCriterion("order_price =", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceNotEqualTo(BigDecimal value) {
			addCriterion("order_price <>", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceGreaterThan(BigDecimal value) {
			addCriterion("order_price >", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("order_price >=", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceLessThan(BigDecimal value) {
			addCriterion("order_price <", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("order_price <=", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceIn(List<BigDecimal> values) {
			addCriterion("order_price in", values, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceNotIn(List<BigDecimal> values) {
			addCriterion("order_price not in", values, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("order_price between", value1, value2, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("order_price not between", value1, value2, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceIsNull() {
			addCriterion("pay_price is null");
			return (Criteria) this;
		}

		public Criteria andPayPriceIsNotNull() {
			addCriterion("pay_price is not null");
			return (Criteria) this;
		}

		public Criteria andPayPriceEqualTo(BigDecimal value) {
			addCriterion("pay_price =", value, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceNotEqualTo(BigDecimal value) {
			addCriterion("pay_price <>", value, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceGreaterThan(BigDecimal value) {
			addCriterion("pay_price >", value, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("pay_price >=", value, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceLessThan(BigDecimal value) {
			addCriterion("pay_price <", value, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("pay_price <=", value, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceIn(List<BigDecimal> values) {
			addCriterion("pay_price in", values, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceNotIn(List<BigDecimal> values) {
			addCriterion("pay_price not in", values, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("pay_price between", value1, value2, "payPrice");
			return (Criteria) this;
		}

		public Criteria andPayPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("pay_price not between", value1, value2, "payPrice");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("pay_time is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("pay_time is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(Date value) {
			addCriterion("pay_time =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(Date value) {
			addCriterion("pay_time <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(Date value) {
			addCriterion("pay_time >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pay_time >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(Date value) {
			addCriterion("pay_time <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(Date value) {
			addCriterion("pay_time <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<Date> values) {
			addCriterion("pay_time in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<Date> values) {
			addCriterion("pay_time not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(Date value1, Date value2) {
			addCriterion("pay_time between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(Date value1, Date value2) {
			addCriterion("pay_time not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andShopServerIdIsNull() {
			addCriterion("shop_server_id is null");
			return (Criteria) this;
		}

		public Criteria andShopServerIdIsNotNull() {
			addCriterion("shop_server_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopServerIdEqualTo(String value) {
			addCriterion("shop_server_id =", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotEqualTo(String value) {
			addCriterion("shop_server_id <>", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdGreaterThan(String value) {
			addCriterion("shop_server_id >", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdGreaterThanOrEqualTo(String value) {
			addCriterion("shop_server_id >=", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdLessThan(String value) {
			addCriterion("shop_server_id <", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdLessThanOrEqualTo(String value) {
			addCriterion("shop_server_id <=", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdLike(String value) {
			addCriterion("shop_server_id like", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotLike(String value) {
			addCriterion("shop_server_id not like", value, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdIn(List<String> values) {
			addCriterion("shop_server_id in", values, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotIn(List<String> values) {
			addCriterion("shop_server_id not in", values, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdBetween(String value1, String value2) {
			addCriterion("shop_server_id between", value1, value2, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andShopServerIdNotBetween(String value1, String value2) {
			addCriterion("shop_server_id not between", value1, value2, "shopServerId");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(Integer value) {
			addCriterion("order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(Integer value) {
			addCriterion("order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(Integer value) {
			addCriterion("order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(Integer value) {
			addCriterion("order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
			addCriterion("order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<Integer> values) {
			addCriterion("order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<Integer> values) {
			addCriterion("order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
			addCriterion("order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("order_status not between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("order_type is null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("order_type is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeEqualTo(Integer value) {
			addCriterion("order_type =", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotEqualTo(Integer value) {
			addCriterion("order_type <>", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThan(Integer value) {
			addCriterion("order_type >", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_type >=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThan(Integer value) {
			addCriterion("order_type <", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(Integer value) {
			addCriterion("order_type <=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIn(List<Integer> values) {
			addCriterion("order_type in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotIn(List<Integer> values) {
			addCriterion("order_type not in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeBetween(Integer value1, Integer value2) {
			addCriterion("order_type between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("order_type not between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderDescIsNull() {
			addCriterion("order_desc is null");
			return (Criteria) this;
		}

		public Criteria andOrderDescIsNotNull() {
			addCriterion("order_desc is not null");
			return (Criteria) this;
		}

		public Criteria andOrderDescEqualTo(String value) {
			addCriterion("order_desc =", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescNotEqualTo(String value) {
			addCriterion("order_desc <>", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescGreaterThan(String value) {
			addCriterion("order_desc >", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescGreaterThanOrEqualTo(String value) {
			addCriterion("order_desc >=", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescLessThan(String value) {
			addCriterion("order_desc <", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescLessThanOrEqualTo(String value) {
			addCriterion("order_desc <=", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescLike(String value) {
			addCriterion("order_desc like", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescNotLike(String value) {
			addCriterion("order_desc not like", value, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescIn(List<String> values) {
			addCriterion("order_desc in", values, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescNotIn(List<String> values) {
			addCriterion("order_desc not in", values, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescBetween(String value1, String value2) {
			addCriterion("order_desc between", value1, value2, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andOrderDescNotBetween(String value1, String value2) {
			addCriterion("order_desc not between", value1, value2, "orderDesc");
			return (Criteria) this;
		}

		public Criteria andPayWayIsNull() {
			addCriterion("pay_way is null");
			return (Criteria) this;
		}

		public Criteria andPayWayIsNotNull() {
			addCriterion("pay_way is not null");
			return (Criteria) this;
		}

		public Criteria andPayWayEqualTo(Integer value) {
			addCriterion("pay_way =", value, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayNotEqualTo(Integer value) {
			addCriterion("pay_way <>", value, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayGreaterThan(Integer value) {
			addCriterion("pay_way >", value, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayGreaterThanOrEqualTo(Integer value) {
			addCriterion("pay_way >=", value, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayLessThan(Integer value) {
			addCriterion("pay_way <", value, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayLessThanOrEqualTo(Integer value) {
			addCriterion("pay_way <=", value, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayIn(List<Integer> values) {
			addCriterion("pay_way in", values, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayNotIn(List<Integer> values) {
			addCriterion("pay_way not in", values, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayBetween(Integer value1, Integer value2) {
			addCriterion("pay_way between", value1, value2, "payWay");
			return (Criteria) this;
		}

		public Criteria andPayWayNotBetween(Integer value1, Integer value2) {
			addCriterion("pay_way not between", value1, value2, "payWay");
			return (Criteria) this;
		}

		public Criteria andServerTimeIsNull() {
			addCriterion("server_time is null");
			return (Criteria) this;
		}

		public Criteria andServerTimeIsNotNull() {
			addCriterion("server_time is not null");
			return (Criteria) this;
		}

		public Criteria andServerTimeEqualTo(Date value) {
			addCriterion("server_time =", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeNotEqualTo(Date value) {
			addCriterion("server_time <>", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeGreaterThan(Date value) {
			addCriterion("server_time >", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("server_time >=", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeLessThan(Date value) {
			addCriterion("server_time <", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeLessThanOrEqualTo(Date value) {
			addCriterion("server_time <=", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeIn(List<Date> values) {
			addCriterion("server_time in", values, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeNotIn(List<Date> values) {
			addCriterion("server_time not in", values, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeBetween(Date value1, Date value2) {
			addCriterion("server_time between", value1, value2, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeNotBetween(Date value1, Date value2) {
			addCriterion("server_time not between", value1, value2, "serverTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeIsNull() {
			addCriterion("close_time is null");
			return (Criteria) this;
		}

		public Criteria andCloseTimeIsNotNull() {
			addCriterion("close_time is not null");
			return (Criteria) this;
		}

		public Criteria andCloseTimeEqualTo(Date value) {
			addCriterion("close_time =", value, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeNotEqualTo(Date value) {
			addCriterion("close_time <>", value, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeGreaterThan(Date value) {
			addCriterion("close_time >", value, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("close_time >=", value, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeLessThan(Date value) {
			addCriterion("close_time <", value, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeLessThanOrEqualTo(Date value) {
			addCriterion("close_time <=", value, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeIn(List<Date> values) {
			addCriterion("close_time in", values, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeNotIn(List<Date> values) {
			addCriterion("close_time not in", values, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeBetween(Date value1, Date value2) {
			addCriterion("close_time between", value1, value2, "closeTime");
			return (Criteria) this;
		}

		public Criteria andCloseTimeNotBetween(Date value1, Date value2) {
			addCriterion("close_time not between", value1, value2, "closeTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIsNull() {
			addCriterion("finish_time is null");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIsNotNull() {
			addCriterion("finish_time is not null");
			return (Criteria) this;
		}

		public Criteria andFinishTimeEqualTo(Date value) {
			addCriterion("finish_time =", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotEqualTo(Date value) {
			addCriterion("finish_time <>", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeGreaterThan(Date value) {
			addCriterion("finish_time >", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("finish_time >=", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeLessThan(Date value) {
			addCriterion("finish_time <", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeLessThanOrEqualTo(Date value) {
			addCriterion("finish_time <=", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIn(List<Date> values) {
			addCriterion("finish_time in", values, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotIn(List<Date> values) {
			addCriterion("finish_time not in", values, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeBetween(Date value1, Date value2) {
			addCriterion("finish_time between", value1, value2, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotBetween(Date value1, Date value2) {
			addCriterion("finish_time not between", value1, value2, "finishTime");
			return (Criteria) this;
		}

		public Criteria andOrderNumIsNull() {
			addCriterion("order_num is null");
			return (Criteria) this;
		}

		public Criteria andOrderNumIsNotNull() {
			addCriterion("order_num is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNumEqualTo(Integer value) {
			addCriterion("order_num =", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumNotEqualTo(Integer value) {
			addCriterion("order_num <>", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumGreaterThan(Integer value) {
			addCriterion("order_num >", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_num >=", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumLessThan(Integer value) {
			addCriterion("order_num <", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumLessThanOrEqualTo(Integer value) {
			addCriterion("order_num <=", value, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumIn(List<Integer> values) {
			addCriterion("order_num in", values, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumNotIn(List<Integer> values) {
			addCriterion("order_num not in", values, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumBetween(Integer value1, Integer value2) {
			addCriterion("order_num between", value1, value2, "orderNum");
			return (Criteria) this;
		}

		public Criteria andOrderNumNotBetween(Integer value1, Integer value2) {
			addCriterion("order_num not between", value1, value2, "orderNum");
			return (Criteria) this;
		}

		public Criteria andServerNameIsNull() {
			addCriterion("server_name is null");
			return (Criteria) this;
		}

		public Criteria andServerNameIsNotNull() {
			addCriterion("server_name is not null");
			return (Criteria) this;
		}

		public Criteria andServerNameEqualTo(String value) {
			addCriterion("server_name =", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotEqualTo(String value) {
			addCriterion("server_name <>", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameGreaterThan(String value) {
			addCriterion("server_name >", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameGreaterThanOrEqualTo(String value) {
			addCriterion("server_name >=", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLessThan(String value) {
			addCriterion("server_name <", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLessThanOrEqualTo(String value) {
			addCriterion("server_name <=", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameLike(String value) {
			addCriterion("server_name like", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotLike(String value) {
			addCriterion("server_name not like", value, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameIn(List<String> values) {
			addCriterion("server_name in", values, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotIn(List<String> values) {
			addCriterion("server_name not in", values, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameBetween(String value1, String value2) {
			addCriterion("server_name between", value1, value2, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerNameNotBetween(String value1, String value2) {
			addCriterion("server_name not between", value1, value2, "serverName");
			return (Criteria) this;
		}

		public Criteria andServerAddressIsNull() {
			addCriterion("server_address is null");
			return (Criteria) this;
		}

		public Criteria andServerAddressIsNotNull() {
			addCriterion("server_address is not null");
			return (Criteria) this;
		}

		public Criteria andServerAddressEqualTo(String value) {
			addCriterion("server_address =", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressNotEqualTo(String value) {
			addCriterion("server_address <>", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressGreaterThan(String value) {
			addCriterion("server_address >", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressGreaterThanOrEqualTo(String value) {
			addCriterion("server_address >=", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressLessThan(String value) {
			addCriterion("server_address <", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressLessThanOrEqualTo(String value) {
			addCriterion("server_address <=", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressLike(String value) {
			addCriterion("server_address like", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressNotLike(String value) {
			addCriterion("server_address not like", value, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressIn(List<String> values) {
			addCriterion("server_address in", values, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressNotIn(List<String> values) {
			addCriterion("server_address not in", values, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressBetween(String value1, String value2) {
			addCriterion("server_address between", value1, value2, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andServerAddressNotBetween(String value1, String value2) {
			addCriterion("server_address not between", value1, value2, "serverAddress");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNull() {
			addCriterion("shop_id is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("shop_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(String value) {
			addCriterion("shop_id =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(String value) {
			addCriterion("shop_id <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(String value) {
			addCriterion("shop_id >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(String value) {
			addCriterion("shop_id >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(String value) {
			addCriterion("shop_id <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(String value) {
			addCriterion("shop_id <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLike(String value) {
			addCriterion("shop_id like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotLike(String value) {
			addCriterion("shop_id not like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<String> values) {
			addCriterion("shop_id in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<String> values) {
			addCriterion("shop_id not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(String value1, String value2) {
			addCriterion("shop_id between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(String value1, String value2) {
			addCriterion("shop_id not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoIsNull() {
			addCriterion("server_member_no is null");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoIsNotNull() {
			addCriterion("server_member_no is not null");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoEqualTo(String value) {
			addCriterion("server_member_no =", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoNotEqualTo(String value) {
			addCriterion("server_member_no <>", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoGreaterThan(String value) {
			addCriterion("server_member_no >", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoGreaterThanOrEqualTo(String value) {
			addCriterion("server_member_no >=", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoLessThan(String value) {
			addCriterion("server_member_no <", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoLessThanOrEqualTo(String value) {
			addCriterion("server_member_no <=", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoLike(String value) {
			addCriterion("server_member_no like", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoNotLike(String value) {
			addCriterion("server_member_no not like", value, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoIn(List<String> values) {
			addCriterion("server_member_no in", values, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoNotIn(List<String> values) {
			addCriterion("server_member_no not in", values, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoBetween(String value1, String value2) {
			addCriterion("server_member_no between", value1, value2, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andServerMemberNoNotBetween(String value1, String value2) {
			addCriterion("server_member_no not between", value1, value2, "serverMemberNo");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckIsNull() {
			addCriterion("shop_is_check is null");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckIsNotNull() {
			addCriterion("shop_is_check is not null");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckEqualTo(Integer value) {
			addCriterion("shop_is_check =", value, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckNotEqualTo(Integer value) {
			addCriterion("shop_is_check <>", value, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckGreaterThan(Integer value) {
			addCriterion("shop_is_check >", value, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckGreaterThanOrEqualTo(Integer value) {
			addCriterion("shop_is_check >=", value, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckLessThan(Integer value) {
			addCriterion("shop_is_check <", value, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckLessThanOrEqualTo(Integer value) {
			addCriterion("shop_is_check <=", value, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckIn(List<Integer> values) {
			addCriterion("shop_is_check in", values, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckNotIn(List<Integer> values) {
			addCriterion("shop_is_check not in", values, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckBetween(Integer value1, Integer value2) {
			addCriterion("shop_is_check between", value1, value2, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andShopIsCheckNotBetween(Integer value1, Integer value2) {
			addCriterion("shop_is_check not between", value1, value2, "shopIsCheck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckIsNull() {
			addCriterion("server_memebr_is_chenck is null");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckIsNotNull() {
			addCriterion("server_memebr_is_chenck is not null");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckEqualTo(Integer value) {
			addCriterion("server_memebr_is_chenck =", value, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckNotEqualTo(Integer value) {
			addCriterion("server_memebr_is_chenck <>", value, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckGreaterThan(Integer value) {
			addCriterion("server_memebr_is_chenck >", value, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckGreaterThanOrEqualTo(Integer value) {
			addCriterion("server_memebr_is_chenck >=", value, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckLessThan(Integer value) {
			addCriterion("server_memebr_is_chenck <", value, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckLessThanOrEqualTo(Integer value) {
			addCriterion("server_memebr_is_chenck <=", value, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckIn(List<Integer> values) {
			addCriterion("server_memebr_is_chenck in", values, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckNotIn(List<Integer> values) {
			addCriterion("server_memebr_is_chenck not in", values, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckBetween(Integer value1, Integer value2) {
			addCriterion("server_memebr_is_chenck between", value1, value2, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andServerMemebrIsChenckNotBetween(Integer value1, Integer value2) {
			addCriterion("server_memebr_is_chenck not between", value1, value2, "serverMemebrIsChenck");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartIsNull() {
			addCriterion("appointment_time_start is null");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartIsNotNull() {
			addCriterion("appointment_time_start is not null");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartEqualTo(Date value) {
			addCriterion("appointment_time_start =", value, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartNotEqualTo(Date value) {
			addCriterion("appointment_time_start <>", value, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartGreaterThan(Date value) {
			addCriterion("appointment_time_start >", value, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartGreaterThanOrEqualTo(Date value) {
			addCriterion("appointment_time_start >=", value, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartLessThan(Date value) {
			addCriterion("appointment_time_start <", value, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartLessThanOrEqualTo(Date value) {
			addCriterion("appointment_time_start <=", value, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartIn(List<Date> values) {
			addCriterion("appointment_time_start in", values, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartNotIn(List<Date> values) {
			addCriterion("appointment_time_start not in", values, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartBetween(Date value1, Date value2) {
			addCriterion("appointment_time_start between", value1, value2, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeStartNotBetween(Date value1, Date value2) {
			addCriterion("appointment_time_start not between", value1, value2, "appointmentTimeStart");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndIsNull() {
			addCriterion("appointment_time_end is null");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndIsNotNull() {
			addCriterion("appointment_time_end is not null");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndEqualTo(Date value) {
			addCriterion("appointment_time_end =", value, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndNotEqualTo(Date value) {
			addCriterion("appointment_time_end <>", value, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndGreaterThan(Date value) {
			addCriterion("appointment_time_end >", value, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndGreaterThanOrEqualTo(Date value) {
			addCriterion("appointment_time_end >=", value, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndLessThan(Date value) {
			addCriterion("appointment_time_end <", value, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndLessThanOrEqualTo(Date value) {
			addCriterion("appointment_time_end <=", value, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndIn(List<Date> values) {
			addCriterion("appointment_time_end in", values, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndNotIn(List<Date> values) {
			addCriterion("appointment_time_end not in", values, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndBetween(Date value1, Date value2) {
			addCriterion("appointment_time_end between", value1, value2, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEndNotBetween(Date value1, Date value2) {
			addCriterion("appointment_time_end not between", value1, value2, "appointmentTimeEnd");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoIsNull() {
			addCriterion("server_example_photo is null");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoIsNotNull() {
			addCriterion("server_example_photo is not null");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoEqualTo(String value) {
			addCriterion("server_example_photo =", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoNotEqualTo(String value) {
			addCriterion("server_example_photo <>", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoGreaterThan(String value) {
			addCriterion("server_example_photo >", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoGreaterThanOrEqualTo(String value) {
			addCriterion("server_example_photo >=", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoLessThan(String value) {
			addCriterion("server_example_photo <", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoLessThanOrEqualTo(String value) {
			addCriterion("server_example_photo <=", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoLike(String value) {
			addCriterion("server_example_photo like", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoNotLike(String value) {
			addCriterion("server_example_photo not like", value, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoIn(List<String> values) {
			addCriterion("server_example_photo in", values, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoNotIn(List<String> values) {
			addCriterion("server_example_photo not in", values, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoBetween(String value1, String value2) {
			addCriterion("server_example_photo between", value1, value2, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andServerExamplePhotoNotBetween(String value1, String value2) {
			addCriterion("server_example_photo not between", value1, value2, "serverExamplePhoto");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneIsNull() {
			addCriterion("order_phone is null");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneIsNotNull() {
			addCriterion("order_phone is not null");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneEqualTo(String value) {
			addCriterion("order_phone =", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneNotEqualTo(String value) {
			addCriterion("order_phone <>", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneGreaterThan(String value) {
			addCriterion("order_phone >", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("order_phone >=", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneLessThan(String value) {
			addCriterion("order_phone <", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneLessThanOrEqualTo(String value) {
			addCriterion("order_phone <=", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneLike(String value) {
			addCriterion("order_phone like", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneNotLike(String value) {
			addCriterion("order_phone not like", value, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneIn(List<String> values) {
			addCriterion("order_phone in", values, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneNotIn(List<String> values) {
			addCriterion("order_phone not in", values, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneBetween(String value1, String value2) {
			addCriterion("order_phone between", value1, value2, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderPhoneNotBetween(String value1, String value2) {
			addCriterion("order_phone not between", value1, value2, "orderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameIsNull() {
			addCriterion("order_nickname is null");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameIsNotNull() {
			addCriterion("order_nickname is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameEqualTo(String value) {
			addCriterion("order_nickname =", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameNotEqualTo(String value) {
			addCriterion("order_nickname <>", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameGreaterThan(String value) {
			addCriterion("order_nickname >", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("order_nickname >=", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameLessThan(String value) {
			addCriterion("order_nickname <", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameLessThanOrEqualTo(String value) {
			addCriterion("order_nickname <=", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameLike(String value) {
			addCriterion("order_nickname like", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameNotLike(String value) {
			addCriterion("order_nickname not like", value, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameIn(List<String> values) {
			addCriterion("order_nickname in", values, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameNotIn(List<String> values) {
			addCriterion("order_nickname not in", values, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameBetween(String value1, String value2) {
			addCriterion("order_nickname between", value1, value2, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andOrderNicknameNotBetween(String value1, String value2) {
			addCriterion("order_nickname not between", value1, value2, "orderNickname");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameIsNull() {
			addCriterion("server_member_name is null");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameIsNotNull() {
			addCriterion("server_member_name is not null");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameEqualTo(String value) {
			addCriterion("server_member_name =", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameNotEqualTo(String value) {
			addCriterion("server_member_name <>", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameGreaterThan(String value) {
			addCriterion("server_member_name >", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameGreaterThanOrEqualTo(String value) {
			addCriterion("server_member_name >=", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameLessThan(String value) {
			addCriterion("server_member_name <", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameLessThanOrEqualTo(String value) {
			addCriterion("server_member_name <=", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameLike(String value) {
			addCriterion("server_member_name like", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameNotLike(String value) {
			addCriterion("server_member_name not like", value, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameIn(List<String> values) {
			addCriterion("server_member_name in", values, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameNotIn(List<String> values) {
			addCriterion("server_member_name not in", values, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameBetween(String value1, String value2) {
			addCriterion("server_member_name between", value1, value2, "serverMemberName");
			return (Criteria) this;
		}

		public Criteria andServerMemberNameNotBetween(String value1, String value2) {
			addCriterion("server_member_name not between", value1, value2, "serverMemberName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}