package com.jisu.WeChatApp.pojo;

import java.util.Date;
import java.util.List;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_name
	 * @mbg.generated
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.descpt
	 * @mbg.generated
	 */
	private String descpt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.code
	 * @mbg.generated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.insertUid
	 * @mbg.generated
	 */
	private Integer insertuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.insertTime
	 * @mbg.generated
	 */
	private Date inserttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.updateTime
	 * @mbg.generated
	 */
	private Date updatetime;
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
	 * @return  the value of role.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}
	//角色下的权限ids
		private List<RolePermission> rolePerms;
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
	 * @param id  the value for role.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_name
	 * @return  the value of role.role_name
	 * @mbg.generated
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_name
	 * @param roleName  the value for role.role_name
	 * @mbg.generated
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.descpt
	 * @return  the value of role.descpt
	 * @mbg.generated
	 */
	public String getDescpt() {
		return descpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.descpt
	 * @param descpt  the value for role.descpt
	 * @mbg.generated
	 */
	public void setDescpt(String descpt) {
		this.descpt = descpt == null ? null : descpt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.code
	 * @return  the value of role.code
	 * @mbg.generated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.code
	 * @param code  the value for role.code
	 * @mbg.generated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.insertUid
	 * @return  the value of role.insertUid
	 * @mbg.generated
	 */
	public Integer getInsertuid() {
		return insertuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.insertUid
	 * @param insertuid  the value for role.insertUid
	 * @mbg.generated
	 */
	public void setInsertuid(Integer insertuid) {
		this.insertuid = insertuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.insertTime
	 * @return  the value of role.insertTime
	 * @mbg.generated
	 */
	public Date getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.insertTime
	 * @param inserttime  the value for role.insertTime
	 * @mbg.generated
	 */
	public void setInserttime(Date inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.updateTime
	 * @return  the value of role.updateTime
	 * @mbg.generated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.updateTime
	 * @param updatetime  the value for role.updateTime
	 * @mbg.generated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public List<RolePermission> getRolePerms() {
		return rolePerms;
	}

	public void setRolePerms(List<RolePermission> rolePerms) {
		this.rolePerms = rolePerms;
	}
}