package com.jisu.WeChatApp.pojo;

public class RolePermissionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permit_id
     *
     * @mbg.generated
     */
    private Integer permitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permit_id
     *
     * @return the value of role_permission.permit_id
     *
     * @mbg.generated
     */
    public Integer getPermitId() {
        return permitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permit_id
     *
     * @param permitId the value for role_permission.permit_id
     *
     * @mbg.generated
     */
    public void setPermitId(Integer permitId) {
        this.permitId = permitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_id
     *
     * @return the value of role_permission.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_id
     *
     * @param roleId the value for role_permission.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}