package com.jisu.WeChatApp.pojo;

import java.util.ArrayList;
import java.util.List;

public class ServerClassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table server_class
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table server_class
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table server_class
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public ServerClassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server_class
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andServerClassIdIsNull() {
            addCriterion("server_class_id is null");
            return (Criteria) this;
        }

        public Criteria andServerClassIdIsNotNull() {
            addCriterion("server_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerClassIdEqualTo(String value) {
            addCriterion("server_class_id =", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotEqualTo(String value) {
            addCriterion("server_class_id <>", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdGreaterThan(String value) {
            addCriterion("server_class_id >", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdGreaterThanOrEqualTo(String value) {
            addCriterion("server_class_id >=", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdLessThan(String value) {
            addCriterion("server_class_id <", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdLessThanOrEqualTo(String value) {
            addCriterion("server_class_id <=", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdLike(String value) {
            addCriterion("server_class_id like", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotLike(String value) {
            addCriterion("server_class_id not like", value, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdIn(List<String> values) {
            addCriterion("server_class_id in", values, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotIn(List<String> values) {
            addCriterion("server_class_id not in", values, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdBetween(String value1, String value2) {
            addCriterion("server_class_id between", value1, value2, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassIdNotBetween(String value1, String value2) {
            addCriterion("server_class_id not between", value1, value2, "serverClassId");
            return (Criteria) this;
        }

        public Criteria andServerClassNameIsNull() {
            addCriterion("server_class_name is null");
            return (Criteria) this;
        }

        public Criteria andServerClassNameIsNotNull() {
            addCriterion("server_class_name is not null");
            return (Criteria) this;
        }

        public Criteria andServerClassNameEqualTo(String value) {
            addCriterion("server_class_name =", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameNotEqualTo(String value) {
            addCriterion("server_class_name <>", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameGreaterThan(String value) {
            addCriterion("server_class_name >", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("server_class_name >=", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameLessThan(String value) {
            addCriterion("server_class_name <", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameLessThanOrEqualTo(String value) {
            addCriterion("server_class_name <=", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameLike(String value) {
            addCriterion("server_class_name like", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameNotLike(String value) {
            addCriterion("server_class_name not like", value, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameIn(List<String> values) {
            addCriterion("server_class_name in", values, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameNotIn(List<String> values) {
            addCriterion("server_class_name not in", values, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameBetween(String value1, String value2) {
            addCriterion("server_class_name between", value1, value2, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassNameNotBetween(String value1, String value2) {
            addCriterion("server_class_name not between", value1, value2, "serverClassName");
            return (Criteria) this;
        }

        public Criteria andServerClassDescIsNull() {
            addCriterion("server_class_desc is null");
            return (Criteria) this;
        }

        public Criteria andServerClassDescIsNotNull() {
            addCriterion("server_class_desc is not null");
            return (Criteria) this;
        }

        public Criteria andServerClassDescEqualTo(String value) {
            addCriterion("server_class_desc =", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescNotEqualTo(String value) {
            addCriterion("server_class_desc <>", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescGreaterThan(String value) {
            addCriterion("server_class_desc >", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescGreaterThanOrEqualTo(String value) {
            addCriterion("server_class_desc >=", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescLessThan(String value) {
            addCriterion("server_class_desc <", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescLessThanOrEqualTo(String value) {
            addCriterion("server_class_desc <=", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescLike(String value) {
            addCriterion("server_class_desc like", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescNotLike(String value) {
            addCriterion("server_class_desc not like", value, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescIn(List<String> values) {
            addCriterion("server_class_desc in", values, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescNotIn(List<String> values) {
            addCriterion("server_class_desc not in", values, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescBetween(String value1, String value2) {
            addCriterion("server_class_desc between", value1, value2, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassDescNotBetween(String value1, String value2) {
            addCriterion("server_class_desc not between", value1, value2, "serverClassDesc");
            return (Criteria) this;
        }

        public Criteria andServerClassImgIsNull() {
            addCriterion("server_class_img is null");
            return (Criteria) this;
        }

        public Criteria andServerClassImgIsNotNull() {
            addCriterion("server_class_img is not null");
            return (Criteria) this;
        }

        public Criteria andServerClassImgEqualTo(String value) {
            addCriterion("server_class_img =", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgNotEqualTo(String value) {
            addCriterion("server_class_img <>", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgGreaterThan(String value) {
            addCriterion("server_class_img >", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgGreaterThanOrEqualTo(String value) {
            addCriterion("server_class_img >=", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgLessThan(String value) {
            addCriterion("server_class_img <", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgLessThanOrEqualTo(String value) {
            addCriterion("server_class_img <=", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgLike(String value) {
            addCriterion("server_class_img like", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgNotLike(String value) {
            addCriterion("server_class_img not like", value, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgIn(List<String> values) {
            addCriterion("server_class_img in", values, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgNotIn(List<String> values) {
            addCriterion("server_class_img not in", values, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgBetween(String value1, String value2) {
            addCriterion("server_class_img between", value1, value2, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassImgNotBetween(String value1, String value2) {
            addCriterion("server_class_img not between", value1, value2, "serverClassImg");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelIsNull() {
            addCriterion("server_class_level is null");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelIsNotNull() {
            addCriterion("server_class_level is not null");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelEqualTo(Integer value) {
            addCriterion("server_class_level =", value, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelNotEqualTo(Integer value) {
            addCriterion("server_class_level <>", value, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelGreaterThan(Integer value) {
            addCriterion("server_class_level >", value, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("server_class_level >=", value, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelLessThan(Integer value) {
            addCriterion("server_class_level <", value, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelLessThanOrEqualTo(Integer value) {
            addCriterion("server_class_level <=", value, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelIn(List<Integer> values) {
            addCriterion("server_class_level in", values, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelNotIn(List<Integer> values) {
            addCriterion("server_class_level not in", values, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelBetween(Integer value1, Integer value2) {
            addCriterion("server_class_level between", value1, value2, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("server_class_level not between", value1, value2, "serverClassLevel");
            return (Criteria) this;
        }

        public Criteria andServerClassPidIsNull() {
            addCriterion("server_class_pid is null");
            return (Criteria) this;
        }

        public Criteria andServerClassPidIsNotNull() {
            addCriterion("server_class_pid is not null");
            return (Criteria) this;
        }

        public Criteria andServerClassPidEqualTo(String value) {
            addCriterion("server_class_pid =", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidNotEqualTo(String value) {
            addCriterion("server_class_pid <>", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidGreaterThan(String value) {
            addCriterion("server_class_pid >", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidGreaterThanOrEqualTo(String value) {
            addCriterion("server_class_pid >=", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidLessThan(String value) {
            addCriterion("server_class_pid <", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidLessThanOrEqualTo(String value) {
            addCriterion("server_class_pid <=", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidLike(String value) {
            addCriterion("server_class_pid like", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidNotLike(String value) {
            addCriterion("server_class_pid not like", value, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidIn(List<String> values) {
            addCriterion("server_class_pid in", values, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidNotIn(List<String> values) {
            addCriterion("server_class_pid not in", values, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidBetween(String value1, String value2) {
            addCriterion("server_class_pid between", value1, value2, "serverClassPid");
            return (Criteria) this;
        }

        public Criteria andServerClassPidNotBetween(String value1, String value2) {
            addCriterion("server_class_pid not between", value1, value2, "serverClassPid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server_class
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server_class
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}