package com.jisu.WeChatApp.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServerMemberInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public ServerMemberInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andServerMemberIdIsNull() {
			addCriterion("server_member_id is null");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdIsNotNull() {
			addCriterion("server_member_id is not null");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdEqualTo(String value) {
			addCriterion("server_member_id =", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdNotEqualTo(String value) {
			addCriterion("server_member_id <>", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdGreaterThan(String value) {
			addCriterion("server_member_id >", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("server_member_id >=", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdLessThan(String value) {
			addCriterion("server_member_id <", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdLessThanOrEqualTo(String value) {
			addCriterion("server_member_id <=", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdLike(String value) {
			addCriterion("server_member_id like", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdNotLike(String value) {
			addCriterion("server_member_id not like", value, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdIn(List<String> values) {
			addCriterion("server_member_id in", values, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdNotIn(List<String> values) {
			addCriterion("server_member_id not in", values, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdBetween(String value1, String value2) {
			addCriterion("server_member_id between", value1, value2, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andServerMemberIdNotBetween(String value1, String value2) {
			addCriterion("server_member_id not between", value1, value2, "serverMemberId");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNull() {
			addCriterion("member_no is null");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNotNull() {
			addCriterion("member_no is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNoEqualTo(String value) {
			addCriterion("member_no =", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotEqualTo(String value) {
			addCriterion("member_no <>", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThan(String value) {
			addCriterion("member_no >", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
			addCriterion("member_no >=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThan(String value) {
			addCriterion("member_no <", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThanOrEqualTo(String value) {
			addCriterion("member_no <=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLike(String value) {
			addCriterion("member_no like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotLike(String value) {
			addCriterion("member_no not like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoIn(List<String> values) {
			addCriterion("member_no in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotIn(List<String> values) {
			addCriterion("member_no not in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoBetween(String value1, String value2) {
			addCriterion("member_no between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotBetween(String value1, String value2) {
			addCriterion("member_no not between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNull() {
			addCriterion("shop_id is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("shop_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(String value) {
			addCriterion("shop_id =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(String value) {
			addCriterion("shop_id <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(String value) {
			addCriterion("shop_id >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(String value) {
			addCriterion("shop_id >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(String value) {
			addCriterion("shop_id <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(String value) {
			addCriterion("shop_id <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLike(String value) {
			addCriterion("shop_id like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotLike(String value) {
			addCriterion("shop_id not like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<String> values) {
			addCriterion("shop_id in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<String> values) {
			addCriterion("shop_id not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(String value1, String value2) {
			addCriterion("shop_id between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(String value1, String value2) {
			addCriterion("shop_id not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescIsNull() {
			addCriterion("server_member_desc is null");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescIsNotNull() {
			addCriterion("server_member_desc is not null");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescEqualTo(String value) {
			addCriterion("server_member_desc =", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescNotEqualTo(String value) {
			addCriterion("server_member_desc <>", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescGreaterThan(String value) {
			addCriterion("server_member_desc >", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescGreaterThanOrEqualTo(String value) {
			addCriterion("server_member_desc >=", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescLessThan(String value) {
			addCriterion("server_member_desc <", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescLessThanOrEqualTo(String value) {
			addCriterion("server_member_desc <=", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescLike(String value) {
			addCriterion("server_member_desc like", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescNotLike(String value) {
			addCriterion("server_member_desc not like", value, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescIn(List<String> values) {
			addCriterion("server_member_desc in", values, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescNotIn(List<String> values) {
			addCriterion("server_member_desc not in", values, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescBetween(String value1, String value2) {
			addCriterion("server_member_desc between", value1, value2, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerMemberDescNotBetween(String value1, String value2) {
			addCriterion("server_member_desc not between", value1, value2, "serverMemberDesc");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrIsNull() {
			addCriterion("server_class_id_str is null");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrIsNotNull() {
			addCriterion("server_class_id_str is not null");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrEqualTo(String value) {
			addCriterion("server_class_id_str =", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrNotEqualTo(String value) {
			addCriterion("server_class_id_str <>", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrGreaterThan(String value) {
			addCriterion("server_class_id_str >", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrGreaterThanOrEqualTo(String value) {
			addCriterion("server_class_id_str >=", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrLessThan(String value) {
			addCriterion("server_class_id_str <", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrLessThanOrEqualTo(String value) {
			addCriterion("server_class_id_str <=", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrLike(String value) {
			addCriterion("server_class_id_str like", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrNotLike(String value) {
			addCriterion("server_class_id_str not like", value, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrIn(List<String> values) {
			addCriterion("server_class_id_str in", values, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrNotIn(List<String> values) {
			addCriterion("server_class_id_str not in", values, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrBetween(String value1, String value2) {
			addCriterion("server_class_id_str between", value1, value2, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andServerClassIdStrNotBetween(String value1, String value2) {
			addCriterion("server_class_id_str not between", value1, value2, "serverClassIdStr");
			return (Criteria) this;
		}

		public Criteria andStratTimeIsNull() {
			addCriterion("strat_time is null");
			return (Criteria) this;
		}

		public Criteria andStratTimeIsNotNull() {
			addCriterion("strat_time is not null");
			return (Criteria) this;
		}

		public Criteria andStratTimeEqualTo(Date value) {
			addCriterion("strat_time =", value, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeNotEqualTo(Date value) {
			addCriterion("strat_time <>", value, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeGreaterThan(Date value) {
			addCriterion("strat_time >", value, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("strat_time >=", value, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeLessThan(Date value) {
			addCriterion("strat_time <", value, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeLessThanOrEqualTo(Date value) {
			addCriterion("strat_time <=", value, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeIn(List<Date> values) {
			addCriterion("strat_time in", values, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeNotIn(List<Date> values) {
			addCriterion("strat_time not in", values, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeBetween(Date value1, Date value2) {
			addCriterion("strat_time between", value1, value2, "stratTime");
			return (Criteria) this;
		}

		public Criteria andStratTimeNotBetween(Date value1, Date value2) {
			addCriterion("strat_time not between", value1, value2, "stratTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterion("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterion("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeIsNull() {
			addCriterion("order_takes_type is null");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeIsNotNull() {
			addCriterion("order_takes_type is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeEqualTo(Integer value) {
			addCriterion("order_takes_type =", value, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeNotEqualTo(Integer value) {
			addCriterion("order_takes_type <>", value, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeGreaterThan(Integer value) {
			addCriterion("order_takes_type >", value, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_takes_type >=", value, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeLessThan(Integer value) {
			addCriterion("order_takes_type <", value, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeLessThanOrEqualTo(Integer value) {
			addCriterion("order_takes_type <=", value, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeIn(List<Integer> values) {
			addCriterion("order_takes_type in", values, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeNotIn(List<Integer> values) {
			addCriterion("order_takes_type not in", values, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeBetween(Integer value1, Integer value2) {
			addCriterion("order_takes_type between", value1, value2, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andOrderTakesTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("order_takes_type not between", value1, value2, "orderTakesType");
			return (Criteria) this;
		}

		public Criteria andInProhiIsNull() {
			addCriterion("in_prohi is null");
			return (Criteria) this;
		}

		public Criteria andInProhiIsNotNull() {
			addCriterion("in_prohi is not null");
			return (Criteria) this;
		}

		public Criteria andInProhiEqualTo(Integer value) {
			addCriterion("in_prohi =", value, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiNotEqualTo(Integer value) {
			addCriterion("in_prohi <>", value, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiGreaterThan(Integer value) {
			addCriterion("in_prohi >", value, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiGreaterThanOrEqualTo(Integer value) {
			addCriterion("in_prohi >=", value, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiLessThan(Integer value) {
			addCriterion("in_prohi <", value, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiLessThanOrEqualTo(Integer value) {
			addCriterion("in_prohi <=", value, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiIn(List<Integer> values) {
			addCriterion("in_prohi in", values, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiNotIn(List<Integer> values) {
			addCriterion("in_prohi not in", values, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiBetween(Integer value1, Integer value2) {
			addCriterion("in_prohi between", value1, value2, "inProhi");
			return (Criteria) this;
		}

		public Criteria andInProhiNotBetween(Integer value1, Integer value2) {
			addCriterion("in_prohi not between", value1, value2, "inProhi");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server_member_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}