package com.jisu.WeChatApp.pojo;

import java.util.Date;

public class ShopPraiseHistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_praise_history.praise_history_id
	 * @mbg.generated
	 */
	private String praiseHistoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_praise_history.shop_id
	 * @mbg.generated
	 */
	private String shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_praise_history.member_on
	 * @mbg.generated
	 */
	private String memberOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_praise_history.create_time
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_praise_history.praise_history_id
	 * @return  the value of shop_praise_history.praise_history_id
	 * @mbg.generated
	 */
	public String getPraiseHistoryId() {
		return praiseHistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_praise_history.praise_history_id
	 * @param praiseHistoryId  the value for shop_praise_history.praise_history_id
	 * @mbg.generated
	 */
	public void setPraiseHistoryId(String praiseHistoryId) {
		this.praiseHistoryId = praiseHistoryId == null ? null : praiseHistoryId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_praise_history.shop_id
	 * @return  the value of shop_praise_history.shop_id
	 * @mbg.generated
	 */
	public String getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_praise_history.shop_id
	 * @param shopId  the value for shop_praise_history.shop_id
	 * @mbg.generated
	 */
	public void setShopId(String shopId) {
		this.shopId = shopId == null ? null : shopId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_praise_history.member_on
	 * @return  the value of shop_praise_history.member_on
	 * @mbg.generated
	 */
	public String getMemberOn() {
		return memberOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_praise_history.member_on
	 * @param memberOn  the value for shop_praise_history.member_on
	 * @mbg.generated
	 */
	public void setMemberOn(String memberOn) {
		this.memberOn = memberOn == null ? null : memberOn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_praise_history.create_time
	 * @return  the value of shop_praise_history.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_praise_history.create_time
	 * @param createTime  the value for shop_praise_history.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}