package com.jisu.WeChatApp.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public ShopInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table shop_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andShopIdIsNull() {
			addCriterion("shop_id is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("shop_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(String value) {
			addCriterion("shop_id =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(String value) {
			addCriterion("shop_id <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(String value) {
			addCriterion("shop_id >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(String value) {
			addCriterion("shop_id >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(String value) {
			addCriterion("shop_id <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(String value) {
			addCriterion("shop_id <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLike(String value) {
			addCriterion("shop_id like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotLike(String value) {
			addCriterion("shop_id not like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<String> values) {
			addCriterion("shop_id in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<String> values) {
			addCriterion("shop_id not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(String value1, String value2) {
			addCriterion("shop_id between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(String value1, String value2) {
			addCriterion("shop_id not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("shop_name is null");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("shop_name is not null");
			return (Criteria) this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("shop_name =", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("shop_name <>", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("shop_name >", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("shop_name >=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("shop_name <", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("shop_name <=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("shop_name like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("shop_name not like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("shop_name in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("shop_name not in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("shop_name between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("shop_name not between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopDescribeIsNull() {
			addCriterion("shop_describe is null");
			return (Criteria) this;
		}

		public Criteria andShopDescribeIsNotNull() {
			addCriterion("shop_describe is not null");
			return (Criteria) this;
		}

		public Criteria andShopDescribeEqualTo(String value) {
			addCriterion("shop_describe =", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeNotEqualTo(String value) {
			addCriterion("shop_describe <>", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeGreaterThan(String value) {
			addCriterion("shop_describe >", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeGreaterThanOrEqualTo(String value) {
			addCriterion("shop_describe >=", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeLessThan(String value) {
			addCriterion("shop_describe <", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeLessThanOrEqualTo(String value) {
			addCriterion("shop_describe <=", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeLike(String value) {
			addCriterion("shop_describe like", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeNotLike(String value) {
			addCriterion("shop_describe not like", value, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeIn(List<String> values) {
			addCriterion("shop_describe in", values, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeNotIn(List<String> values) {
			addCriterion("shop_describe not in", values, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeBetween(String value1, String value2) {
			addCriterion("shop_describe between", value1, value2, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopDescribeNotBetween(String value1, String value2) {
			addCriterion("shop_describe not between", value1, value2, "shopDescribe");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlIsNull() {
			addCriterion("shop_photo_url is null");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlIsNotNull() {
			addCriterion("shop_photo_url is not null");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlEqualTo(String value) {
			addCriterion("shop_photo_url =", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlNotEqualTo(String value) {
			addCriterion("shop_photo_url <>", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlGreaterThan(String value) {
			addCriterion("shop_photo_url >", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlGreaterThanOrEqualTo(String value) {
			addCriterion("shop_photo_url >=", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlLessThan(String value) {
			addCriterion("shop_photo_url <", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlLessThanOrEqualTo(String value) {
			addCriterion("shop_photo_url <=", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlLike(String value) {
			addCriterion("shop_photo_url like", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlNotLike(String value) {
			addCriterion("shop_photo_url not like", value, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlIn(List<String> values) {
			addCriterion("shop_photo_url in", values, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlNotIn(List<String> values) {
			addCriterion("shop_photo_url not in", values, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlBetween(String value1, String value2) {
			addCriterion("shop_photo_url between", value1, value2, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhotoUrlNotBetween(String value1, String value2) {
			addCriterion("shop_photo_url not between", value1, value2, "shopPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andShopAddressIsNull() {
			addCriterion("shop_address is null");
			return (Criteria) this;
		}

		public Criteria andShopAddressIsNotNull() {
			addCriterion("shop_address is not null");
			return (Criteria) this;
		}

		public Criteria andShopAddressEqualTo(String value) {
			addCriterion("shop_address =", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressNotEqualTo(String value) {
			addCriterion("shop_address <>", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressGreaterThan(String value) {
			addCriterion("shop_address >", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressGreaterThanOrEqualTo(String value) {
			addCriterion("shop_address >=", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressLessThan(String value) {
			addCriterion("shop_address <", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressLessThanOrEqualTo(String value) {
			addCriterion("shop_address <=", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressLike(String value) {
			addCriterion("shop_address like", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressNotLike(String value) {
			addCriterion("shop_address not like", value, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressIn(List<String> values) {
			addCriterion("shop_address in", values, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressNotIn(List<String> values) {
			addCriterion("shop_address not in", values, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressBetween(String value1, String value2) {
			addCriterion("shop_address between", value1, value2, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopAddressNotBetween(String value1, String value2) {
			addCriterion("shop_address not between", value1, value2, "shopAddress");
			return (Criteria) this;
		}

		public Criteria andShopShengIsNull() {
			addCriterion("shop_sheng is null");
			return (Criteria) this;
		}

		public Criteria andShopShengIsNotNull() {
			addCriterion("shop_sheng is not null");
			return (Criteria) this;
		}

		public Criteria andShopShengEqualTo(String value) {
			addCriterion("shop_sheng =", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengNotEqualTo(String value) {
			addCriterion("shop_sheng <>", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengGreaterThan(String value) {
			addCriterion("shop_sheng >", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengGreaterThanOrEqualTo(String value) {
			addCriterion("shop_sheng >=", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengLessThan(String value) {
			addCriterion("shop_sheng <", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengLessThanOrEqualTo(String value) {
			addCriterion("shop_sheng <=", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengLike(String value) {
			addCriterion("shop_sheng like", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengNotLike(String value) {
			addCriterion("shop_sheng not like", value, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengIn(List<String> values) {
			addCriterion("shop_sheng in", values, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengNotIn(List<String> values) {
			addCriterion("shop_sheng not in", values, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengBetween(String value1, String value2) {
			addCriterion("shop_sheng between", value1, value2, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShengNotBetween(String value1, String value2) {
			addCriterion("shop_sheng not between", value1, value2, "shopSheng");
			return (Criteria) this;
		}

		public Criteria andShopShiIsNull() {
			addCriterion("shop_shi is null");
			return (Criteria) this;
		}

		public Criteria andShopShiIsNotNull() {
			addCriterion("shop_shi is not null");
			return (Criteria) this;
		}

		public Criteria andShopShiEqualTo(String value) {
			addCriterion("shop_shi =", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiNotEqualTo(String value) {
			addCriterion("shop_shi <>", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiGreaterThan(String value) {
			addCriterion("shop_shi >", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiGreaterThanOrEqualTo(String value) {
			addCriterion("shop_shi >=", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiLessThan(String value) {
			addCriterion("shop_shi <", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiLessThanOrEqualTo(String value) {
			addCriterion("shop_shi <=", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiLike(String value) {
			addCriterion("shop_shi like", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiNotLike(String value) {
			addCriterion("shop_shi not like", value, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiIn(List<String> values) {
			addCriterion("shop_shi in", values, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiNotIn(List<String> values) {
			addCriterion("shop_shi not in", values, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiBetween(String value1, String value2) {
			addCriterion("shop_shi between", value1, value2, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopShiNotBetween(String value1, String value2) {
			addCriterion("shop_shi not between", value1, value2, "shopShi");
			return (Criteria) this;
		}

		public Criteria andShopQuIsNull() {
			addCriterion("shop_qu is null");
			return (Criteria) this;
		}

		public Criteria andShopQuIsNotNull() {
			addCriterion("shop_qu is not null");
			return (Criteria) this;
		}

		public Criteria andShopQuEqualTo(String value) {
			addCriterion("shop_qu =", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuNotEqualTo(String value) {
			addCriterion("shop_qu <>", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuGreaterThan(String value) {
			addCriterion("shop_qu >", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuGreaterThanOrEqualTo(String value) {
			addCriterion("shop_qu >=", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuLessThan(String value) {
			addCriterion("shop_qu <", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuLessThanOrEqualTo(String value) {
			addCriterion("shop_qu <=", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuLike(String value) {
			addCriterion("shop_qu like", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuNotLike(String value) {
			addCriterion("shop_qu not like", value, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuIn(List<String> values) {
			addCriterion("shop_qu in", values, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuNotIn(List<String> values) {
			addCriterion("shop_qu not in", values, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuBetween(String value1, String value2) {
			addCriterion("shop_qu between", value1, value2, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopQuNotBetween(String value1, String value2) {
			addCriterion("shop_qu not between", value1, value2, "shopQu");
			return (Criteria) this;
		}

		public Criteria andShopStatusIsNull() {
			addCriterion("shop_status is null");
			return (Criteria) this;
		}

		public Criteria andShopStatusIsNotNull() {
			addCriterion("shop_status is not null");
			return (Criteria) this;
		}

		public Criteria andShopStatusEqualTo(Integer value) {
			addCriterion("shop_status =", value, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusNotEqualTo(Integer value) {
			addCriterion("shop_status <>", value, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusGreaterThan(Integer value) {
			addCriterion("shop_status >", value, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("shop_status >=", value, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusLessThan(Integer value) {
			addCriterion("shop_status <", value, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusLessThanOrEqualTo(Integer value) {
			addCriterion("shop_status <=", value, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusIn(List<Integer> values) {
			addCriterion("shop_status in", values, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusNotIn(List<Integer> values) {
			addCriterion("shop_status not in", values, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusBetween(Integer value1, Integer value2) {
			addCriterion("shop_status between", value1, value2, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andShopStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("shop_status not between", value1, value2, "shopStatus");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlIsNull() {
			addCriterion("shop_logo_url is null");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlIsNotNull() {
			addCriterion("shop_logo_url is not null");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlEqualTo(String value) {
			addCriterion("shop_logo_url =", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlNotEqualTo(String value) {
			addCriterion("shop_logo_url <>", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlGreaterThan(String value) {
			addCriterion("shop_logo_url >", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlGreaterThanOrEqualTo(String value) {
			addCriterion("shop_logo_url >=", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlLessThan(String value) {
			addCriterion("shop_logo_url <", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlLessThanOrEqualTo(String value) {
			addCriterion("shop_logo_url <=", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlLike(String value) {
			addCriterion("shop_logo_url like", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlNotLike(String value) {
			addCriterion("shop_logo_url not like", value, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlIn(List<String> values) {
			addCriterion("shop_logo_url in", values, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlNotIn(List<String> values) {
			addCriterion("shop_logo_url not in", values, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlBetween(String value1, String value2) {
			addCriterion("shop_logo_url between", value1, value2, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopLogoUrlNotBetween(String value1, String value2) {
			addCriterion("shop_logo_url not between", value1, value2, "shopLogoUrl");
			return (Criteria) this;
		}

		public Criteria andShopPhoneIsNull() {
			addCriterion("shop_phone is null");
			return (Criteria) this;
		}

		public Criteria andShopPhoneIsNotNull() {
			addCriterion("shop_phone is not null");
			return (Criteria) this;
		}

		public Criteria andShopPhoneEqualTo(String value) {
			addCriterion("shop_phone =", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneNotEqualTo(String value) {
			addCriterion("shop_phone <>", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneGreaterThan(String value) {
			addCriterion("shop_phone >", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("shop_phone >=", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneLessThan(String value) {
			addCriterion("shop_phone <", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneLessThanOrEqualTo(String value) {
			addCriterion("shop_phone <=", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneLike(String value) {
			addCriterion("shop_phone like", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneNotLike(String value) {
			addCriterion("shop_phone not like", value, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneIn(List<String> values) {
			addCriterion("shop_phone in", values, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneNotIn(List<String> values) {
			addCriterion("shop_phone not in", values, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneBetween(String value1, String value2) {
			addCriterion("shop_phone between", value1, value2, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andShopPhoneNotBetween(String value1, String value2) {
			addCriterion("shop_phone not between", value1, value2, "shopPhone");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIsNull() {
			addCriterion("praise_points is null");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIsNotNull() {
			addCriterion("praise_points is not null");
			return (Criteria) this;
		}

		public Criteria andPraisePointsEqualTo(Integer value) {
			addCriterion("praise_points =", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotEqualTo(Integer value) {
			addCriterion("praise_points <>", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsGreaterThan(Integer value) {
			addCriterion("praise_points >", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsGreaterThanOrEqualTo(Integer value) {
			addCriterion("praise_points >=", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsLessThan(Integer value) {
			addCriterion("praise_points <", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsLessThanOrEqualTo(Integer value) {
			addCriterion("praise_points <=", value, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsIn(List<Integer> values) {
			addCriterion("praise_points in", values, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotIn(List<Integer> values) {
			addCriterion("praise_points not in", values, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsBetween(Integer value1, Integer value2) {
			addCriterion("praise_points between", value1, value2, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andPraisePointsNotBetween(Integer value1, Integer value2) {
			addCriterion("praise_points not between", value1, value2, "praisePoints");
			return (Criteria) this;
		}

		public Criteria andShopClassIdIsNull() {
			addCriterion("shop_class_id is null");
			return (Criteria) this;
		}

		public Criteria andShopClassIdIsNotNull() {
			addCriterion("shop_class_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopClassIdEqualTo(String value) {
			addCriterion("shop_class_id =", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdNotEqualTo(String value) {
			addCriterion("shop_class_id <>", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdGreaterThan(String value) {
			addCriterion("shop_class_id >", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdGreaterThanOrEqualTo(String value) {
			addCriterion("shop_class_id >=", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdLessThan(String value) {
			addCriterion("shop_class_id <", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdLessThanOrEqualTo(String value) {
			addCriterion("shop_class_id <=", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdLike(String value) {
			addCriterion("shop_class_id like", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdNotLike(String value) {
			addCriterion("shop_class_id not like", value, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdIn(List<String> values) {
			addCriterion("shop_class_id in", values, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdNotIn(List<String> values) {
			addCriterion("shop_class_id not in", values, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdBetween(String value1, String value2) {
			addCriterion("shop_class_id between", value1, value2, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopClassIdNotBetween(String value1, String value2) {
			addCriterion("shop_class_id not between", value1, value2, "shopClassId");
			return (Criteria) this;
		}

		public Criteria andShopXIsNull() {
			addCriterion("shop_x is null");
			return (Criteria) this;
		}

		public Criteria andShopXIsNotNull() {
			addCriterion("shop_x is not null");
			return (Criteria) this;
		}

		public Criteria andShopXEqualTo(BigDecimal value) {
			addCriterion("shop_x =", value, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXNotEqualTo(BigDecimal value) {
			addCriterion("shop_x <>", value, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXGreaterThan(BigDecimal value) {
			addCriterion("shop_x >", value, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("shop_x >=", value, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXLessThan(BigDecimal value) {
			addCriterion("shop_x <", value, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXLessThanOrEqualTo(BigDecimal value) {
			addCriterion("shop_x <=", value, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXIn(List<BigDecimal> values) {
			addCriterion("shop_x in", values, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXNotIn(List<BigDecimal> values) {
			addCriterion("shop_x not in", values, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("shop_x between", value1, value2, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopXNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("shop_x not between", value1, value2, "shopX");
			return (Criteria) this;
		}

		public Criteria andShopYIsNull() {
			addCriterion("shop_y is null");
			return (Criteria) this;
		}

		public Criteria andShopYIsNotNull() {
			addCriterion("shop_y is not null");
			return (Criteria) this;
		}

		public Criteria andShopYEqualTo(BigDecimal value) {
			addCriterion("shop_y =", value, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYNotEqualTo(BigDecimal value) {
			addCriterion("shop_y <>", value, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYGreaterThan(BigDecimal value) {
			addCriterion("shop_y >", value, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("shop_y >=", value, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYLessThan(BigDecimal value) {
			addCriterion("shop_y <", value, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYLessThanOrEqualTo(BigDecimal value) {
			addCriterion("shop_y <=", value, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYIn(List<BigDecimal> values) {
			addCriterion("shop_y in", values, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYNotIn(List<BigDecimal> values) {
			addCriterion("shop_y not in", values, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("shop_y between", value1, value2, "shopY");
			return (Criteria) this;
		}

		public Criteria andShopYNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("shop_y not between", value1, value2, "shopY");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNull() {
			addCriterion("member_no is null");
			return (Criteria) this;
		}

		public Criteria andMemberNoIsNotNull() {
			addCriterion("member_no is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNoEqualTo(String value) {
			addCriterion("member_no =", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotEqualTo(String value) {
			addCriterion("member_no <>", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThan(String value) {
			addCriterion("member_no >", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoGreaterThanOrEqualTo(String value) {
			addCriterion("member_no >=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThan(String value) {
			addCriterion("member_no <", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLessThanOrEqualTo(String value) {
			addCriterion("member_no <=", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoLike(String value) {
			addCriterion("member_no like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotLike(String value) {
			addCriterion("member_no not like", value, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoIn(List<String> values) {
			addCriterion("member_no in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotIn(List<String> values) {
			addCriterion("member_no not in", values, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoBetween(String value1, String value2) {
			addCriterion("member_no between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andMemberNoNotBetween(String value1, String value2) {
			addCriterion("member_no not between", value1, value2, "memberNo");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlIsNull() {
			addCriterion("authorization_book_url is null");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlIsNotNull() {
			addCriterion("authorization_book_url is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlEqualTo(String value) {
			addCriterion("authorization_book_url =", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlNotEqualTo(String value) {
			addCriterion("authorization_book_url <>", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlGreaterThan(String value) {
			addCriterion("authorization_book_url >", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlGreaterThanOrEqualTo(String value) {
			addCriterion("authorization_book_url >=", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlLessThan(String value) {
			addCriterion("authorization_book_url <", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlLessThanOrEqualTo(String value) {
			addCriterion("authorization_book_url <=", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlLike(String value) {
			addCriterion("authorization_book_url like", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlNotLike(String value) {
			addCriterion("authorization_book_url not like", value, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlIn(List<String> values) {
			addCriterion("authorization_book_url in", values, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlNotIn(List<String> values) {
			addCriterion("authorization_book_url not in", values, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlBetween(String value1, String value2) {
			addCriterion("authorization_book_url between", value1, value2, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andAuthorizationBookUrlNotBetween(String value1, String value2) {
			addCriterion("authorization_book_url not between", value1, value2, "authorizationBookUrl");
			return (Criteria) this;
		}

		public Criteria andQqIsNull() {
			addCriterion("qq is null");
			return (Criteria) this;
		}

		public Criteria andQqIsNotNull() {
			addCriterion("qq is not null");
			return (Criteria) this;
		}

		public Criteria andQqEqualTo(String value) {
			addCriterion("qq =", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotEqualTo(String value) {
			addCriterion("qq <>", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThan(String value) {
			addCriterion("qq >", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThanOrEqualTo(String value) {
			addCriterion("qq >=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThan(String value) {
			addCriterion("qq <", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThanOrEqualTo(String value) {
			addCriterion("qq <=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLike(String value) {
			addCriterion("qq like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotLike(String value) {
			addCriterion("qq not like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqIn(List<String> values) {
			addCriterion("qq in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotIn(List<String> values) {
			addCriterion("qq not in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqBetween(String value1, String value2) {
			addCriterion("qq between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotBetween(String value1, String value2) {
			addCriterion("qq not between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andWechatIsNull() {
			addCriterion("weChat is null");
			return (Criteria) this;
		}

		public Criteria andWechatIsNotNull() {
			addCriterion("weChat is not null");
			return (Criteria) this;
		}

		public Criteria andWechatEqualTo(String value) {
			addCriterion("weChat =", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotEqualTo(String value) {
			addCriterion("weChat <>", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatGreaterThan(String value) {
			addCriterion("weChat >", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatGreaterThanOrEqualTo(String value) {
			addCriterion("weChat >=", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatLessThan(String value) {
			addCriterion("weChat <", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatLessThanOrEqualTo(String value) {
			addCriterion("weChat <=", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatLike(String value) {
			addCriterion("weChat like", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotLike(String value) {
			addCriterion("weChat not like", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatIn(List<String> values) {
			addCriterion("weChat in", values, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotIn(List<String> values) {
			addCriterion("weChat not in", values, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatBetween(String value1, String value2) {
			addCriterion("weChat between", value1, value2, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotBetween(String value1, String value2) {
			addCriterion("weChat not between", value1, value2, "wechat");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdIsNull() {
			addCriterion("operator_member_id is null");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdIsNotNull() {
			addCriterion("operator_member_id is not null");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdEqualTo(String value) {
			addCriterion("operator_member_id =", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdNotEqualTo(String value) {
			addCriterion("operator_member_id <>", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdGreaterThan(String value) {
			addCriterion("operator_member_id >", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("operator_member_id >=", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdLessThan(String value) {
			addCriterion("operator_member_id <", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdLessThanOrEqualTo(String value) {
			addCriterion("operator_member_id <=", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdLike(String value) {
			addCriterion("operator_member_id like", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdNotLike(String value) {
			addCriterion("operator_member_id not like", value, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdIn(List<String> values) {
			addCriterion("operator_member_id in", values, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdNotIn(List<String> values) {
			addCriterion("operator_member_id not in", values, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdBetween(String value1, String value2) {
			addCriterion("operator_member_id between", value1, value2, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andOperatorMemberIdNotBetween(String value1, String value2) {
			addCriterion("operator_member_id not between", value1, value2, "operatorMemberId");
			return (Criteria) this;
		}

		public Criteria andIsOpenIsNull() {
			addCriterion("is_open is null");
			return (Criteria) this;
		}

		public Criteria andIsOpenIsNotNull() {
			addCriterion("is_open is not null");
			return (Criteria) this;
		}

		public Criteria andIsOpenEqualTo(Integer value) {
			addCriterion("is_open =", value, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenNotEqualTo(Integer value) {
			addCriterion("is_open <>", value, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenGreaterThan(Integer value) {
			addCriterion("is_open >", value, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_open >=", value, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenLessThan(Integer value) {
			addCriterion("is_open <", value, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenLessThanOrEqualTo(Integer value) {
			addCriterion("is_open <=", value, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenIn(List<Integer> values) {
			addCriterion("is_open in", values, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenNotIn(List<Integer> values) {
			addCriterion("is_open not in", values, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenBetween(Integer value1, Integer value2) {
			addCriterion("is_open between", value1, value2, "isOpen");
			return (Criteria) this;
		}

		public Criteria andIsOpenNotBetween(Integer value1, Integer value2) {
			addCriterion("is_open not between", value1, value2, "isOpen");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andIsDefaultIsNull() {
			addCriterion("is_default is null");
			return (Criteria) this;
		}

		public Criteria andIsDefaultIsNotNull() {
			addCriterion("is_default is not null");
			return (Criteria) this;
		}

		public Criteria andIsDefaultEqualTo(Integer value) {
			addCriterion("is_default =", value, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultNotEqualTo(Integer value) {
			addCriterion("is_default <>", value, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultGreaterThan(Integer value) {
			addCriterion("is_default >", value, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_default >=", value, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultLessThan(Integer value) {
			addCriterion("is_default <", value, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultLessThanOrEqualTo(Integer value) {
			addCriterion("is_default <=", value, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultIn(List<Integer> values) {
			addCriterion("is_default in", values, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultNotIn(List<Integer> values) {
			addCriterion("is_default not in", values, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultBetween(Integer value1, Integer value2) {
			addCriterion("is_default between", value1, value2, "isDefault");
			return (Criteria) this;
		}

		public Criteria andIsDefaultNotBetween(Integer value1, Integer value2) {
			addCriterion("is_default not between", value1, value2, "isDefault");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlIsNull() {
			addCriterion("desc_photo_url is null");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlIsNotNull() {
			addCriterion("desc_photo_url is not null");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlEqualTo(String value) {
			addCriterion("desc_photo_url =", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlNotEqualTo(String value) {
			addCriterion("desc_photo_url <>", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlGreaterThan(String value) {
			addCriterion("desc_photo_url >", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlGreaterThanOrEqualTo(String value) {
			addCriterion("desc_photo_url >=", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlLessThan(String value) {
			addCriterion("desc_photo_url <", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlLessThanOrEqualTo(String value) {
			addCriterion("desc_photo_url <=", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlLike(String value) {
			addCriterion("desc_photo_url like", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlNotLike(String value) {
			addCriterion("desc_photo_url not like", value, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlIn(List<String> values) {
			addCriterion("desc_photo_url in", values, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlNotIn(List<String> values) {
			addCriterion("desc_photo_url not in", values, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlBetween(String value1, String value2) {
			addCriterion("desc_photo_url between", value1, value2, "descPhotoUrl");
			return (Criteria) this;
		}

		public Criteria andDescPhotoUrlNotBetween(String value1, String value2) {
			addCriterion("desc_photo_url not between", value1, value2, "descPhotoUrl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table shop_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}