package com.jisu.WeChatApp.pojo;

import java.math.BigDecimal;

public class ShopServer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.shop_server_id
	 * @mbg.generated
	 */
	private String shopServerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_name
	 * @mbg.generated
	 */
	private String serverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_price
	 * @mbg.generated
	 */
	private BigDecimal serverPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_sale_num
	 * @mbg.generated
	 */
	private Integer serverSaleNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_desc
	 * @mbg.generated
	 */
	private String serverDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_url
	 * @mbg.generated
	 */
	private String serverUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.shop_id
	 * @mbg.generated
	 */
	private String shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_sale_price
	 * @mbg.generated
	 */
	private BigDecimal serverSalePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_class_id
	 * @mbg.generated
	 */
	private String serverClassId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop_server.server_type
	 * @mbg.generated
	 */
	private Integer serverType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.shop_server_id
	 * @return  the value of shop_server.shop_server_id
	 * @mbg.generated
	 */
	public String getShopServerId() {
		return shopServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.shop_server_id
	 * @param shopServerId  the value for shop_server.shop_server_id
	 * @mbg.generated
	 */
	public void setShopServerId(String shopServerId) {
		this.shopServerId = shopServerId == null ? null : shopServerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_name
	 * @return  the value of shop_server.server_name
	 * @mbg.generated
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_name
	 * @param serverName  the value for shop_server.server_name
	 * @mbg.generated
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName == null ? null : serverName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_price
	 * @return  the value of shop_server.server_price
	 * @mbg.generated
	 */
	public BigDecimal getServerPrice() {
		return serverPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_price
	 * @param serverPrice  the value for shop_server.server_price
	 * @mbg.generated
	 */
	public void setServerPrice(BigDecimal serverPrice) {
		this.serverPrice = serverPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_sale_num
	 * @return  the value of shop_server.server_sale_num
	 * @mbg.generated
	 */
	public Integer getServerSaleNum() {
		return serverSaleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_sale_num
	 * @param serverSaleNum  the value for shop_server.server_sale_num
	 * @mbg.generated
	 */
	public void setServerSaleNum(Integer serverSaleNum) {
		this.serverSaleNum = serverSaleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_desc
	 * @return  the value of shop_server.server_desc
	 * @mbg.generated
	 */
	public String getServerDesc() {
		return serverDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_desc
	 * @param serverDesc  the value for shop_server.server_desc
	 * @mbg.generated
	 */
	public void setServerDesc(String serverDesc) {
		this.serverDesc = serverDesc == null ? null : serverDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_url
	 * @return  the value of shop_server.server_url
	 * @mbg.generated
	 */
	public String getServerUrl() {
		return serverUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_url
	 * @param serverUrl  the value for shop_server.server_url
	 * @mbg.generated
	 */
	public void setServerUrl(String serverUrl) {
		this.serverUrl = serverUrl == null ? null : serverUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.shop_id
	 * @return  the value of shop_server.shop_id
	 * @mbg.generated
	 */
	public String getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.shop_id
	 * @param shopId  the value for shop_server.shop_id
	 * @mbg.generated
	 */
	public void setShopId(String shopId) {
		this.shopId = shopId == null ? null : shopId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_sale_price
	 * @return  the value of shop_server.server_sale_price
	 * @mbg.generated
	 */
	public BigDecimal getServerSalePrice() {
		return serverSalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_sale_price
	 * @param serverSalePrice  the value for shop_server.server_sale_price
	 * @mbg.generated
	 */
	public void setServerSalePrice(BigDecimal serverSalePrice) {
		this.serverSalePrice = serverSalePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_class_id
	 * @return  the value of shop_server.server_class_id
	 * @mbg.generated
	 */
	public String getServerClassId() {
		return serverClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_class_id
	 * @param serverClassId  the value for shop_server.server_class_id
	 * @mbg.generated
	 */
	public void setServerClassId(String serverClassId) {
		this.serverClassId = serverClassId == null ? null : serverClassId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop_server.server_type
	 * @return  the value of shop_server.server_type
	 * @mbg.generated
	 */
	public Integer getServerType() {
		return serverType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop_server.server_type
	 * @param serverType  the value for shop_server.server_type
	 * @mbg.generated
	 */
	public void setServerType(Integer serverType) {
		this.serverType = serverType;
	}
}