package com.jisu.WeChatApp.pojo;

import java.util.Date;

public class SuggestionsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestions_info.suggestions_id
     *
     * @mbg.generated
     */
    private String suggestionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestions_info.suggestions_text
     *
     * @mbg.generated
     */
    private String suggestionsText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestions_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestions_info.contact_away
     *
     * @mbg.generated
     */
    private String contactAway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestions_info.suggestions_type
     *
     * @mbg.generated
     */
    private Integer suggestionsType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestions_info.suggestions_id
     *
     * @return the value of suggestions_info.suggestions_id
     *
     * @mbg.generated
     */
    public String getSuggestionsId() {
        return suggestionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestions_info.suggestions_id
     *
     * @param suggestionsId the value for suggestions_info.suggestions_id
     *
     * @mbg.generated
     */
    public void setSuggestionsId(String suggestionsId) {
        this.suggestionsId = suggestionsId == null ? null : suggestionsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestions_info.suggestions_text
     *
     * @return the value of suggestions_info.suggestions_text
     *
     * @mbg.generated
     */
    public String getSuggestionsText() {
        return suggestionsText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestions_info.suggestions_text
     *
     * @param suggestionsText the value for suggestions_info.suggestions_text
     *
     * @mbg.generated
     */
    public void setSuggestionsText(String suggestionsText) {
        this.suggestionsText = suggestionsText == null ? null : suggestionsText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestions_info.create_time
     *
     * @return the value of suggestions_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestions_info.create_time
     *
     * @param createTime the value for suggestions_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestions_info.contact_away
     *
     * @return the value of suggestions_info.contact_away
     *
     * @mbg.generated
     */
    public String getContactAway() {
        return contactAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestions_info.contact_away
     *
     * @param contactAway the value for suggestions_info.contact_away
     *
     * @mbg.generated
     */
    public void setContactAway(String contactAway) {
        this.contactAway = contactAway == null ? null : contactAway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestions_info.suggestions_type
     *
     * @return the value of suggestions_info.suggestions_type
     *
     * @mbg.generated
     */
    public Integer getSuggestionsType() {
        return suggestionsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestions_info.suggestions_type
     *
     * @param suggestionsType the value for suggestions_info.suggestions_type
     *
     * @mbg.generated
     */
    public void setSuggestionsType(Integer suggestionsType) {
        this.suggestionsType = suggestionsType;
    }
}