package com.jisu.WeChatApp.pojo;

import java.math.BigDecimal;

public class WalletInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_info.wallet_id
     *
     * @mbg.generated
     */
    private String walletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_info.member_no
     *
     * @mbg.generated
     */
    private String memberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_info.rmb
     *
     * @mbg.generated
     */
    private BigDecimal rmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_info.wallet_id
     *
     * @return the value of wallet_info.wallet_id
     *
     * @mbg.generated
     */
    public String getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_info.wallet_id
     *
     * @param walletId the value for wallet_info.wallet_id
     *
     * @mbg.generated
     */
    public void setWalletId(String walletId) {
        this.walletId = walletId == null ? null : walletId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_info.member_no
     *
     * @return the value of wallet_info.member_no
     *
     * @mbg.generated
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_info.member_no
     *
     * @param memberNo the value for wallet_info.member_no
     *
     * @mbg.generated
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_info.rmb
     *
     * @return the value of wallet_info.rmb
     *
     * @mbg.generated
     */
    public BigDecimal getRmb() {
        return rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_info.rmb
     *
     * @param rmb the value for wallet_info.rmb
     *
     * @mbg.generated
     */
    public void setRmb(BigDecimal rmb) {
        this.rmb = rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_info.password
     *
     * @return the value of wallet_info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_info.password
     *
     * @param password the value for wallet_info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}