package com.jisu.WeChatApp.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class WithdrawalRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.withdrawal_record_id
     *
     * @mbg.generated
     */
    private String withdrawalRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.withdrawal_price
     *
     * @mbg.generated
     */
    private BigDecimal withdrawalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.withdrawal_status
     *
     * @mbg.generated
     */
    private Integer withdrawalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.member_no
     *
     * @mbg.generated
     */
    private String memberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.service_charge
     *
     * @mbg.generated
     */
    private BigDecimal serviceCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal feeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.refuse_note
     *
     * @mbg.generated
     */
    private String refuseNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.refuse_time
     *
     * @mbg.generated
     */
    private Date refuseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_record.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.withdrawal_record_id
     *
     * @return the value of withdrawal_record.withdrawal_record_id
     *
     * @mbg.generated
     */
    public String getWithdrawalRecordId() {
        return withdrawalRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.withdrawal_record_id
     *
     * @param withdrawalRecordId the value for withdrawal_record.withdrawal_record_id
     *
     * @mbg.generated
     */
    public void setWithdrawalRecordId(String withdrawalRecordId) {
        this.withdrawalRecordId = withdrawalRecordId == null ? null : withdrawalRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.withdrawal_price
     *
     * @return the value of withdrawal_record.withdrawal_price
     *
     * @mbg.generated
     */
    public BigDecimal getWithdrawalPrice() {
        return withdrawalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.withdrawal_price
     *
     * @param withdrawalPrice the value for withdrawal_record.withdrawal_price
     *
     * @mbg.generated
     */
    public void setWithdrawalPrice(BigDecimal withdrawalPrice) {
        this.withdrawalPrice = withdrawalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.withdrawal_status
     *
     * @return the value of withdrawal_record.withdrawal_status
     *
     * @mbg.generated
     */
    public Integer getWithdrawalStatus() {
        return withdrawalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.withdrawal_status
     *
     * @param withdrawalStatus the value for withdrawal_record.withdrawal_status
     *
     * @mbg.generated
     */
    public void setWithdrawalStatus(Integer withdrawalStatus) {
        this.withdrawalStatus = withdrawalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.member_no
     *
     * @return the value of withdrawal_record.member_no
     *
     * @mbg.generated
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.member_no
     *
     * @param memberNo the value for withdrawal_record.member_no
     *
     * @mbg.generated
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.create_time
     *
     * @return the value of withdrawal_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.create_time
     *
     * @param createTime the value for withdrawal_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.service_charge
     *
     * @return the value of withdrawal_record.service_charge
     *
     * @mbg.generated
     */
    public BigDecimal getServiceCharge() {
        return serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.service_charge
     *
     * @param serviceCharge the value for withdrawal_record.service_charge
     *
     * @mbg.generated
     */
    public void setServiceCharge(BigDecimal serviceCharge) {
        this.serviceCharge = serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.fee_rate
     *
     * @return the value of withdrawal_record.fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.fee_rate
     *
     * @param feeRate the value for withdrawal_record.fee_rate
     *
     * @mbg.generated
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.refuse_note
     *
     * @return the value of withdrawal_record.refuse_note
     *
     * @mbg.generated
     */
    public String getRefuseNote() {
        return refuseNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.refuse_note
     *
     * @param refuseNote the value for withdrawal_record.refuse_note
     *
     * @mbg.generated
     */
    public void setRefuseNote(String refuseNote) {
        this.refuseNote = refuseNote == null ? null : refuseNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.refuse_time
     *
     * @return the value of withdrawal_record.refuse_time
     *
     * @mbg.generated
     */
    public Date getRefuseTime() {
        return refuseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.refuse_time
     *
     * @param refuseTime the value for withdrawal_record.refuse_time
     *
     * @mbg.generated
     */
    public void setRefuseTime(Date refuseTime) {
        this.refuseTime = refuseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_record.finish_time
     *
     * @return the value of withdrawal_record.finish_time
     *
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_record.finish_time
     *
     * @param finishTime the value for withdrawal_record.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
}