package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.BestServerClass;
import com.jisu.WeChatApp.pojo.BestServerClassExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BestServerClassMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	long countByExample(BestServerClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int deleteByExample(BestServerClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String bestServerClassId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int insert(BestServerClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int insertSelective(BestServerClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	List<BestServerClass> selectByExample(BestServerClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	BestServerClass selectByPrimaryKey(String bestServerClassId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") BestServerClass record, @Param("example") BestServerClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") BestServerClass record, @Param("example") BestServerClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BestServerClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table best_server_class
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BestServerClass record);
}