package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.ExperienceInfo;
import com.jisu.WeChatApp.pojo.ExperienceInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ExperienceInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	long countByExample(ExperienceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int deleteByExample(ExperienceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String experienceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int insert(ExperienceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int insertSelective(ExperienceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	List<ExperienceInfo> selectByExample(ExperienceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	ExperienceInfo selectByPrimaryKey(String experienceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ExperienceInfo record, @Param("example") ExperienceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ExperienceInfo record, @Param("example") ExperienceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ExperienceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experience_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ExperienceInfo record);
}