package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.FormInfo;
import com.jisu.WeChatApp.pojo.FormInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FormInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	long countByExample(FormInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int deleteByExample(FormInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String formInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int insert(FormInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int insertSelective(FormInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	List<FormInfo> selectByExample(FormInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	FormInfo selectByPrimaryKey(String formInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") FormInfo record, @Param("example") FormInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") FormInfo record, @Param("example") FormInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(FormInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table form_info
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKey(FormInfo record);
}