package com.jisu.WeChatApp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.jisu.WeChatApp.pojo.LableInfo;
import com.jisu.WeChatApp.pojo.LableInfoExample;

@Mapper
public interface LableInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	long countByExample(LableInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int deleteByExample(LableInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String lableId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int insert(LableInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int insertSelective(LableInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	List<LableInfo> selectByExample(LableInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	LableInfo selectByPrimaryKey(String lableId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") LableInfo record, @Param("example") LableInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") LableInfo record, @Param("example") LableInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(LableInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table lable_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(LableInfo record);
}