package com.jisu.WeChatApp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.jisu.WeChatApp.pojo.MemberInfo;
import com.jisu.WeChatApp.pojo.MemberInfoExample;
import com.jisu.WeChatApp.pojo.UserSearchDTO;
@Mapper
public interface MemberInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	long countByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int deleteByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String memberNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int insert(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int insertSelective(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	List<MemberInfo> selectByExample(MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	MemberInfo selectByPrimaryKey(String memberNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MemberInfo record);

	MemberInfo getMemberInfoByUserName(String username);
	
	List<MemberInfo> getUser(@Param(value = "userSearch")UserSearchDTO userSearch);
}