package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.MemberProhi;
import com.jisu.WeChatApp.pojo.MemberProhiExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MemberProhiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	long countByExample(MemberProhiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int deleteByExample(MemberProhiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String memberProhiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int insert(MemberProhi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int insertSelective(MemberProhi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	List<MemberProhi> selectByExample(MemberProhiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	MemberProhi selectByPrimaryKey(String memberProhiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") MemberProhi record, @Param("example") MemberProhiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") MemberProhi record, @Param("example") MemberProhiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MemberProhi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_prohi
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MemberProhi record);
}