package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.OperatorMember;
import com.jisu.WeChatApp.pojo.OperatorMemberExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface OperatorMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    long countByExample(OperatorMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String operatorMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int insert(OperatorMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int insertSelective(OperatorMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    List<OperatorMember> selectByExample(OperatorMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    OperatorMember selectByPrimaryKey(String operatorMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperatorMember record, @Param("example") OperatorMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperatorMember record, @Param("example") OperatorMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperatorMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperatorMember record);
}