package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.RefundOrderInfo;
import com.jisu.WeChatApp.pojo.RefundOrderInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RefundOrderInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	long countByExample(RefundOrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int deleteByExample(RefundOrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String refundOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int insert(RefundOrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int insertSelective(RefundOrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	List<RefundOrderInfo> selectByExample(RefundOrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	RefundOrderInfo selectByPrimaryKey(String refundOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") RefundOrderInfo record,
			@Param("example") RefundOrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") RefundOrderInfo record, @Param("example") RefundOrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RefundOrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table refund_order_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RefundOrderInfo record);
}