package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.RotationMap;
import com.jisu.WeChatApp.pojo.RotationMapExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RotationMapMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	long countByExample(RotationMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int deleteByExample(RotationMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String rotationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int insert(RotationMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int insertSelective(RotationMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	List<RotationMap> selectByExample(RotationMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	RotationMap selectByPrimaryKey(String rotationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") RotationMap record, @Param("example") RotationMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") RotationMap record, @Param("example") RotationMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RotationMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rotation_map
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RotationMap record);

	List<RotationMap> findAll();
}