package com.jisu.WeChatApp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.jisu.WeChatApp.pojo.ServerClass;
import com.jisu.WeChatApp.pojo.ServerClassExample;
@Mapper
public interface ServerClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    long countByExample(ServerClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int deleteByExample(ServerClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String serverClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int insert(ServerClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int insertSelective(ServerClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    List<ServerClass> selectByExample(ServerClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    ServerClass selectByPrimaryKey(String serverClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ServerClass record, @Param("example") ServerClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ServerClass record, @Param("example") ServerClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServerClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServerClass record);

	List<ServerClass> findAll();

	List<ServerClass> findChildPerm(String id);
}