package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.ServerMemberInfo;
import com.jisu.WeChatApp.pojo.ServerMemberInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ServerMemberInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	long countByExample(ServerMemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int deleteByExample(ServerMemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String serverMemberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int insert(ServerMemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int insertSelective(ServerMemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	List<ServerMemberInfo> selectByExample(ServerMemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	ServerMemberInfo selectByPrimaryKey(String serverMemberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ServerMemberInfo record, @Param("example") ServerMemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ServerMemberInfo record, @Param("example") ServerMemberInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ServerMemberInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_member_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ServerMemberInfo record);
}