package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.ShopPraiseHistory;
import com.jisu.WeChatApp.pojo.ShopPraiseHistoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ShopPraiseHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	long countByExample(ShopPraiseHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int deleteByExample(ShopPraiseHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String praiseHistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int insert(ShopPraiseHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int insertSelective(ShopPraiseHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	List<ShopPraiseHistory> selectByExample(ShopPraiseHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	ShopPraiseHistory selectByPrimaryKey(String praiseHistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ShopPraiseHistory record,
			@Param("example") ShopPraiseHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ShopPraiseHistory record, @Param("example") ShopPraiseHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ShopPraiseHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_praise_history
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ShopPraiseHistory record);
}