package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.ShopLablePraiseHistroy;
import com.jisu.WeChatApp.pojo.ShopLablePraiseHistroyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ShopLablePraiseHistroyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	long countByExample(ShopLablePraiseHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int deleteByExample(ShopLablePraiseHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String shopLablePraiseHistroyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int insert(ShopLablePraiseHistroy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int insertSelective(ShopLablePraiseHistroy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	List<ShopLablePraiseHistroy> selectByExample(ShopLablePraiseHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	ShopLablePraiseHistroy selectByPrimaryKey(String shopLablePraiseHistroyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ShopLablePraiseHistroy record,
			@Param("example") ShopLablePraiseHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ShopLablePraiseHistroy record,
			@Param("example") ShopLablePraiseHistroyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ShopLablePraiseHistroy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_lable_praise_histroy
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ShopLablePraiseHistroy record);
}