package com.jisu.WeChatApp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.jisu.WeChatApp.pojo.ShopLable;
import com.jisu.WeChatApp.pojo.ShopLableExample;

@Mapper
public interface ShopLableMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	long countByExample(ShopLableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int deleteByExample(ShopLableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String shopLableId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int insert(ShopLable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int insertSelective(ShopLable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	List<ShopLable> selectByExample(ShopLableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	ShopLable selectByPrimaryKey(String shopLableId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ShopLable record, @Param("example") ShopLableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ShopLable record, @Param("example") ShopLableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ShopLable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table shop_lable
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ShopLable record);
}