package com.jisu.WeChatApp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.jisu.WeChatApp.pojo.ShopClass;
import com.jisu.WeChatApp.pojo.ShopClassExample;
@Mapper
public interface ShopClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    long countByExample(ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int deleteByExample(ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String shopClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int insert(ShopClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int insertSelective(ShopClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    List<ShopClass> selectByExample(ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    ShopClass selectByPrimaryKey(String shopClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopClass record, @Param("example") ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopClass record, @Param("example") ShopClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopClass record);
}