package com.jisu.WeChatApp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.jisu.WeChatApp.pojo.ShopServer;
import com.jisu.WeChatApp.pojo.ShopServerExample;
@Mapper
public interface ShopServerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	long countByExample(ShopServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int deleteByExample(ShopServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String shopServerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int insert(ShopServer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int insertSelective(ShopServer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	List<ShopServer> selectByExample(ShopServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	ShopServer selectByPrimaryKey(String shopServerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ShopServer record, @Param("example") ShopServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ShopServer record, @Param("example") ShopServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ShopServer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_server
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ShopServer record);
}