package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.ShopInfo;
import com.jisu.WeChatApp.pojo.ShopInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ShopInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	long countByExample(ShopInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int deleteByExample(ShopInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String shopId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int insert(ShopInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int insertSelective(ShopInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	List<ShopInfo> selectByExample(ShopInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	ShopInfo selectByPrimaryKey(String shopId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ShopInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ShopInfo record);
	
	List<ShopInfo> getAllShopList();
}