package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.SuggestionsInfo;
import com.jisu.WeChatApp.pojo.SuggestionsInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SuggestionsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    long countByExample(SuggestionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int deleteByExample(SuggestionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String suggestionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int insert(SuggestionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int insertSelective(SuggestionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    List<SuggestionsInfo> selectByExample(SuggestionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    SuggestionsInfo selectByPrimaryKey(String suggestionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SuggestionsInfo record, @Param("example") SuggestionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SuggestionsInfo record, @Param("example") SuggestionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SuggestionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SuggestionsInfo record);
}