package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.WalletInfo;
import com.jisu.WeChatApp.pojo.WalletInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WalletInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	long countByExample(WalletInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int deleteByExample(WalletInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String walletId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int insert(WalletInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int insertSelective(WalletInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	List<WalletInfo> selectByExample(WalletInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	WalletInfo selectByPrimaryKey(String walletId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") WalletInfo record, @Param("example") WalletInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") WalletInfo record, @Param("example") WalletInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(WalletInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table wallet_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(WalletInfo record);
}