package com.jisu.WeChatApp.dao;

import com.jisu.WeChatApp.pojo.WithdrawalRecord;
import com.jisu.WeChatApp.pojo.WithdrawalRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WithdrawalRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	long countByExample(WithdrawalRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int deleteByExample(WithdrawalRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String withdrawalRecordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int insert(WithdrawalRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int insertSelective(WithdrawalRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	List<WithdrawalRecord> selectByExample(WithdrawalRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	WithdrawalRecord selectByPrimaryKey(String withdrawalRecordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") WithdrawalRecord record, @Param("example") WithdrawalRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") WithdrawalRecord record, @Param("example") WithdrawalRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(WithdrawalRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table withdrawal_record
	 * @mbg.generated
	 */
	int updateByPrimaryKey(WithdrawalRecord record);
}